#!/usr/bin/env node
/* The gauge — the smallest thing that can be a world, run against the shared suite.
   Every leak in docs/TAGS.md was found by READING the engine. Nobody had ever built a second
   world to find out which one a real pack hits FIRST, so this is that world: five tiles, two
   people, one room, in content/gauge/. It is not a game and is never linked from one. Its only
   job is to fail in the places a new game would fail, out loud, on every CI run.
   The shell is GENERATED from the public index rather than copied, because ~770 of its ~800
   lines must be identical (the shared suite reads about twenty element ids straight out of it)
   and a copy would rot silently the first time index.html changed. Every edit below asserts it
   actually matched: a String.replace that stops matching returns the input unchanged and would
   otherwise print success while testing the wrong thing.
   Run:  node test/gauge.js          */
const fs = require('fs'), path = require('path'), { execFileSync } = require('child_process');
const root = path.resolve(__dirname, '..');
const SCRIPTS = ['strings', 'quests.en', 'quests.es', 'npcs', 'maps', 'art', 'config'];

let h = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const edit = (what, re, to) => {
  const before = h;
  h = h.replace(re, to);
  if (h === before) throw new Error('the gauge shell can no longer be built from index.html: the "' + what + '" edit matched nothing. index.html changed shape — fix this generator, do not commit a hand-made copy.');
};

// the pack's own scripts, in the order the public shell loads Meridian's
edit('script tags',
  /<script src="content\/meridian\/strings\.js"><\/script>[\s\S]*?<script src="content\/meridian\/docs\.js"><\/script>/,
  SCRIPTS.map(s => '<script src="' + s + '.js"></script>').join('\n'));
// depth: content/gauge/index.html is two folders down from the root the public shell sits in
edit('engine paths', /<script src="(engine\/|vendor\/|qr\.js)/g, '<script src="../../$1');
edit('title', /<title>[^<]*<\/title>/, '<title>El Faro — the gauge pack</title>');
// a fixture must not claim to be an installable app, and must not fight the real one for a cache
edit('manifest', /<link rel="manifest"[^>]*>/, '<!-- no manifest: the gauge is a fixture, not an app -->');
edit('service worker', /navigator\.serviceWorker\.register\([^)]*\)/, 'Promise.reject(new Error("the gauge never installs a service worker"))');

if (h.includes('content/meridian/')) throw new Error('the generated gauge shell still loads Meridian content');
SCRIPTS.forEach(s => { if (!h.includes('"' + s + '.js"')) throw new Error('the generated gauge shell never loads ' + s + '.js'); });

const shellPath = path.join(root, 'content', 'gauge', 'index.html');
fs.writeFileSync(shellPath, h);
console.log('gauge shell built from index.html (' + h.split('\n').length + ' lines, ' + SCRIPTS.length + ' pack scripts)');

/* ---------- THE SECOND GAUGE: the camera the owner actually plays (2026-09-22) ----------
   El Faro declares CAMERAS=["top","front"] and that line is LOAD-BEARING — it is the only proof in
   this repository that engine/boot.js skips a 149 KB library for a world that does not want 3D. So
   it is not flipped. A SECOND shell is generated beside it that declares all four, and the result
   is the first time anything here has measured what a brand-new world looks like in the camera the
   owner plays. Until today that answer was nobody's: every 3D demand the engine makes of a new pack
   — the shape library, the flat-tile audit, the bake, the contact shadow — was exercised only by
   the two games that already have art of their own.
   Generated, never committed, and every edit asserts it matched (docs/GAUGE.md: a String.replace
   that stops matching returns the input unchanged and would print success while testing the wrong
   thing). */
const cfgPath = path.join(root, 'content', 'gauge', 'config.js');
let cfg = fs.readFileSync(cfgPath, 'utf8');
const cedit = (what, re, to) => { const before = cfg; cfg = cfg.replace(re, to);
  if (cfg === before) throw new Error('the 3D gauge config can no longer be built: the "' + what + '" edit matched nothing in content/gauge/config.js — fix this generator, do not commit a hand-made copy.'); };
cedit('CAMERAS', /const CAMERAS=\[[^\]]*\];/, 'const CAMERAS=["top","front","iso","3d"];');
cedit('CAMDEF', /const CAMDEF="[^"]*";/, 'const CAMDEF="3d";');
cedit('storage prefix', /const STOREPFX="gauge";/, 'const STOREPFX="gauge3d";');
cfg = '/* GENERATED by test/gauge.js from content/gauge/config.js - never commit a copy.\n' +
      '   The same five-tile world, asked to stand up in all four cameras. */\n' + cfg;
if (!/\["top","front","iso","3d"\]/.test(cfg)) throw new Error('the 3D gauge config does not declare four cameras');
fs.writeFileSync(path.join(root, 'content', 'gauge', 'config-3d.js'), cfg);

let h3 = h;
{ const before = h3; h3 = h3.replace('<script src="config.js"></script>', '<script src="config-3d.js"></script>');
  if (h3 === before) throw new Error('the 3D gauge shell can no longer be built: it does not load config.js'); }
{ const before = h3; h3 = h3.replace(/<title>[^<]*<\/title>/, '<title>El Faro en 3D \u2014 the gauge pack, four cameras</title>');
  if (h3 === before) throw new Error('the 3D gauge shell has no title to replace'); }
if (h3.includes('"config.js"')) throw new Error('the 3D gauge shell still loads the two-camera config');
fs.writeFileSync(path.join(root, 'content', 'gauge', 'index-3d.html'), h3);
console.log('gauge 3D shell built beside it (four cameras, its own storage prefix)');

/* The gauge does NOT chase green, and that is the whole point of it.
   Six of the shared suite's checks fail this pack for being SMALL rather than for being WRONG —
   "no facade has two windows", "no tall piece was found", "the check never ran". They are honest
   about it and they fail the build anyway, which means the suite advertised as runnable against
   ANY pack cannot be passed by the smallest pack that is a world. docs/NEW-WORLD.md §5 makes the
   shared suite step 3 and a minimal pack step 2, so today the gate rejects the thing the step
   before it produces.
   So this records what a new world is up against and fails when that CHANGES. A line that
   disappears means the template got easier — good, delete it here and say so. A line that appears
   means somebody made the engine harder to write a second game for, and it says so on the day it
   happens instead of in somebody's month two. */
function measure(shell, expectedFile, label) {
const expectedPath = path.join(root, 'content', 'gauge', expectedFile);
let out = '';
try {
  out = execFileSync('node', [path.join(root, 'test', 'engine.smoke.js'), '--index', shell],
    { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
} catch (e) { out = (e.stdout || '') + (e.stderr || ''); }

const got = out.split('\n').filter(l => l.startsWith('- ')).map(l => l.slice(2).trim())
  // one line carries a live frame count; the number is noise, the fact is not
  .map(l => l.replace(/drawn \d+ time\(s\)/, 'drawn N time(s)')).sort();

/* A gauge that cannot RUN must never report that the template got easier.
   2026-09-16: the shared suite could not launch a browser (the container's chromium was a
   version behind what playwright-core resolves), so the inner run died before a single check
   fired. `got` came back empty, every expected line looked "no longer demanded", and this file
   printed six lines of GOOD NEWS about an engine it had never asked a question of. That is the
   silent zero this whole fixture exists to catch, happening inside the fixture — so it is now
   the first thing checked, and it fails differently, because "nothing to measure" is not a
   measurement (docs/GAUGE.md). */
if (!got.length) {
  console.log('FAIL — ' + label + ' never ran. The shared suite produced no findings at all, which is');
  console.log('not the same as finding nothing. This is a broken run, not an easier template.');
  console.log('Most often: no usable Chromium. Set CHROMIUM_PATH to a real binary and try again.');
  console.log('--- what the inner run actually said ---');
  console.log(out.trim().split('\n').slice(-20).join('\n') || '(it said nothing at all)');
  return 1;
}

if (!fs.existsSync(expectedPath)) {
  fs.writeFileSync(expectedPath, got.join('\n') + '\n');
  console.log(label + ': first run — recorded ' + got.length + ' standing demands in content/gauge/' + expectedFile);
  return 0;
}
const want = fs.readFileSync(expectedPath, 'utf8').split('\n').map(l => l.trim()).filter(Boolean).sort();
const gone = want.filter(l => !got.includes(l)), fresh = got.filter(l => !want.includes(l));

if (!gone.length && !fresh.length) {
  console.log('OK — ' + label + ': a five-tile, two-person, one-room world still boots, plays and meets the engine on the same ' + want.length + ' terms as before.');
  return 0;
}
console.log('FAIL — what the engine demands of a brand-new world has CHANGED (' + label + ').');
fresh.forEach(l => console.log('  NEW demand on every future game: ' + l));
gone.forEach(l => console.log('  no longer demanded (the template got easier — delete this line from content/gauge/' + expectedFile + ' and say so in the commit): ' + l));
return 1;
}

/* BOTH shells, every run. The two-camera one is the older measurement and the only proof that the
   library is skipped for a world that declined 3D; the four-camera one is the first time this
   repository has asked what a brand-new world costs in the camera the owner plays. Either failing
   fails the build, and neither short-circuits the other — a run that stops at the first failure
   tells you half of what changed. */
const rc = measure('content/gauge/index.html', 'expected.txt', 'the gauge')
         | measure('content/gauge/index-3d.html', 'expected-3d.txt', 'the gauge in 3D');
process.exit(rc ? 1 : 0);
