const {chromium}=require('playwright-core');
const W=+process.argv[2],H=+process.argv[3],TAG=process.argv[4];
(async()=>{
 const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--use-gl=swiftshader','--enable-unsafe-swiftshader']});
 const p=await b.newPage({viewport:{width:W,height:H},deviceScaleFactor:2});
 p.on('pageerror',e=>console.log('PAGEERR',e.message));
 await p.goto('file:///home/user/meridian-quest/changarrito/index.html');
 await p.waitForTimeout(900);
 await p.click('.classes button[data-c="architect"]'); await p.waitForTimeout(200);
 await p.click('#begin'); await p.waitForTimeout(700);
 await p.evaluate(()=>{world='hq';px=fx=3;py=fy=2;dir='left';showWorld();checkTalk();});
 await p.waitForTimeout(500);
 await p.click('#talk'); await p.waitForTimeout(500);
 await p.evaluate(()=>{const b=[...document.querySelectorAll('#reader button')].find(x=>/build something/i.test(x.textContent));b.click();});
 await p.waitForTimeout(700);
 const d=await p.evaluate(()=>{const R=e=>{const r=e.getBoundingClientRect();return {x:Math.round(r.x),y:Math.round(r.y),w:Math.round(r.width),h:Math.round(r.height),b:Math.round(r.bottom),r2:Math.round(r.right)};};
   const rd=document.getElementById('reader'),paper=document.getElementById('paperSheet');
   const fields=[...document.querySelectorAll('#reader .dfl')].map(e=>({lb:e.textContent.trim().slice(0,30),...R(e)}));
   const btns=[...document.querySelectorAll('#reader .dfrow button, #reader .docbar button')].map(e=>({t:e.textContent.trim().slice(0,20),cls:e.className||e.parentElement.className,...R(e)}));
   const tas=[...document.querySelectorAll('#reader textarea')].map(e=>({h:Math.round(e.getBoundingClientRect().height),cs:getComputedStyle(e).height}));
   return {vw:innerWidth,vh:innerHeight,readerScrollH:rd.scrollHeight,readerClientH:rd.clientHeight,readerScrollW:rd.scrollWidth,readerClientW:rd.clientWidth,paper:R(paper),fields,btns,tas,docScrollW:document.documentElement.scrollWidth};});
 console.log(TAG,JSON.stringify(d,null,1));
 await b.close();
})();
