const {chromium}=require('playwright-core');
const W=+process.argv[2],H=+process.argv[3],TAG=process.argv[4];
(async()=>{
 const b=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--use-gl=swiftshader','--enable-unsafe-swiftshader']});
 const p=await b.newPage({viewport:{width:W,height:H},deviceScaleFactor:2});
 p.on('pageerror',e=>console.log('PAGEERR',e.message));
 await p.goto('file:///home/user/meridian-quest/changarrito/index.html');
 await p.waitForTimeout(900);
 await p.click('.classes button[data-c="architect"]'); await p.waitForTimeout(200);
 await p.click('#begin'); await p.waitForTimeout(700);
 await p.evaluate(()=>{world='hq';px=fx=3;py=fy=2;dir='left';showWorld();checkTalk();});
 await p.waitForTimeout(800);
 const t=await p.evaluate(()=>{const e=document.getElementById('talk');return e&&e.offsetParent!==null?e.textContent:null;});
 console.log(TAG,'talk btn:',t);
 await p.screenshot({path:`/tmp/rosa/${TAG}-50-nexttoguero.png`});
 await p.click('#talk').catch(e=>console.log('no talk'));
 await p.waitForTimeout(700);
 await p.screenshot({path:`/tmp/rosa/${TAG}-51-talkcard.png`});
 const c=await p.evaluate(()=>{const R=e=>{const r=e.getBoundingClientRect();return {x:Math.round(r.x),y:Math.round(r.y),w:Math.round(r.width),h:Math.round(r.height),b:Math.round(r.bottom)};};
   const card=document.getElementById('card');
   const btns=[...document.querySelectorAll('#card button')].filter(b=>b.offsetParent).map(b=>({t:b.textContent.trim().slice(0,26),...R(b)}));
   return {vh:innerHeight,card:card&&!card.hidden?R(card):null,scrollY:Math.round(scrollY),docH:document.documentElement.scrollHeight,btns};});
 console.log(TAG,'CARD',JSON.stringify(c));
 await b.close();
})();
