/* Meridian Quest content pack — NPC roster: emoji, names (EN/ES), looks, and world placement. */
const NPCE={priya:"🛠️",marcus:"💼",camila:"🎧",tovar:"🌮",legal:"⚖️",cto:"🏥",junior:"🐣",ceo:"👑",fred:"🐕",rosa:"🌶️",chuy:"👨‍🍳",guero:"👷",lupe:"📐",beto:"🔨",kike:"🧱",mari:"🏗️",xochi:"🧵",chelo:"🛒",nando:"📦",perla:"🧮",chava:"🔪"};
const NPCN={
 en:{priya:"Priya · Engineering Lead",marcus:"Marcus · CFO",camila:"Camila · Customer Success",tovar:"Ops Director · Tovar's Tacos",legal:"Dana · Legal",cto:"Dr. Okafor · Bayview CTO",junior:"Theo · Junior PM",ceo:"CEO · Tovar's Tacos",fred:"Frederick · Good Boy",rosa:"Doña Rosa · Owner, La Cocina",chuy:"Chuy · Head Cook",guero:"Don Güero · Foreman, La Obra",lupe:"Lupe · Estimator & Permits",beto:"Beto · Crew, La Obra",kike:"Kike · Mason",mari:"Mari · Crane Operator",xochi:"Xochi · Designer",chelo:"Doña Chelo · Owner, El Mercado",nando:"Nando · Receiving & Systems",perla:"Perla · Counter & Numbers",chava:"Chava · Carnicero"},
 es:{priya:"Priya · Líder de Ingeniería",marcus:"Marcus · CFO",camila:"Camila · Éxito del Cliente",tovar:"Director de Operaciones · Tovar's Tacos",legal:"Dana · Legal",cto:"Dr. Okafor · CTO de Bayview",junior:"Theo · PM Junior",ceo:"CEO · Tovar's Tacos",fred:"Frederick · Buen Chico",rosa:"Doña Rosa · Dueña de La Cocina",chuy:"Chuy · Jefe de Cocina",guero:"Don Güero · Maestro de Obra",lupe:"Lupe · Presupuestos y Permisos",beto:"Beto · Cuadrilla de La Obra",kike:"Kike · Albañil",mari:"Mari · Operadora de Grúa",xochi:"Xochi · Diseñadora",chelo:"Doña Chelo · Dueña, El Mercado",nando:"Nando · Recibo y Sistemas",perla:"Perla · Mostrador y Números",chava:"Chava · Carnicero"}};
/* npc letter -> npc key + quest queue */
const STATIONS={p:{npc:"priya",q:[5,14]},j:{npc:"junior",q:[7]},c:{npc:"ceo",q:[9]},l:{npc:"legal",q:[2]},
                t:{npc:"tovar",q:[0,8]},a:{npc:"camila",q:[1]},h:{npc:"cto",q:[6]},m:{npc:"marcus",q:[3,4]}};
const WNPC={hq:STATIONS,lc:{r:{npc:"rosa",q:[10]},y:{npc:"chuy",q:[11]}},st:{f:{npc:"guero",q:[12]},e:{npc:"lupe",q:[13]}},
            ex:{w:{npc:"beto",q:[],chat:1},x:{npc:"kike",q:[],chat:1},z:{npc:"mari",q:[],chat:1}},
            lo:{d:{npc:"xochi",q:[15],chat:1}},
            me:{s:{npc:"chelo",q:[17,20]},n:{npc:"nando",q:[16,19]},u:{npc:"perla",q:[18],chat:1},v:{npc:"chava",q:[],chat:1}}};
const NPCLOOK={p:{shirt:"#C2543F",skin:"#B97E52",hair:"#171219",style:"long"},j:{shirt:"#3E8ED0",skin:"#EFC49A",hair:"#7A4A22",style:"curly"},
  c:{shirt:"#2C2637",skin:"#D9995F",hair:"#5C5C66",style:"cap",outfit:"formal"},l:{shirt:"#25423C",skin:"#F0C9A6",hair:"#2C1C12",style:"long",outfit:"formal"},
  t:{shirt:"#D08A2E",skin:"#C08356",hair:"#1E1620",style:"cap"},a:{shirt:"#B04A78",skin:"#8C5A33",hair:"#241B26",style:"curly"},
  h:{shirt:"#31446E",skin:"#E8B98C",hair:"#403830",style:"buzz",outfit:"formal"},m:{shirt:"#3A415C",skin:"#F1CDA9",hair:"#8E8E96",style:"buzz",outfit:"formal"},
  r:{shirt:"#B23A48",skin:"#C08356",hair:"#B9B9C0",style:"long"},y:{shirt:"#F0EEE6",skin:"#B97E52",hair:"#26202B",style:"buzz"},
  f:{shirt:"#E8720C",skin:"#B97E52",hair:"#9A9AA2",style:"buzz"},e:{shirt:"#2E7F86",skin:"#E5AC82",hair:"#26202B",style:"pony"},
  w:{shirt:"#3E6FA8",skin:"#B97E52",hair:"#26202B",style:"buzz",hat:"hard"},x:{shirt:"#7A8752",skin:"#C08356",hair:"#26202B",style:"buzz",hat:"hard"},z:{shirt:"#A85C86",skin:"#E5AC82",hair:"#26202B",style:"pony",hat:"hard"},
  d:{shirt:"#C4586B",skin:"#C08356",hair:"#26202B",style:"buns"},
  s:{shirt:"#8E3B5C",skin:"#C08356",hair:"#B9B9C0",style:"buns"},n:{shirt:"#2E6E8E",skin:"#B97E52",hair:"#26202B",style:"fade"},
  u:{shirt:"#E0A430",skin:"#E5AC82",hair:"#171219",style:"pony"},v:{shirt:"#F0EEE6",skin:"#8C5A33",hair:"#26202B",style:"edgar"}};
/* chill townsfolk: chat-only characters with no quests — they just vibe. The engine
   spawns them at boot; their chatter comes from UI.chill (strings.js) unless a name
   matches an egg below. The owner can create more in admin mode (🧍 brush). */
const CHILL=[
 {name:{en:"Nacho · Mural Painter",es:"Nacho · Muralista"},world:"st",x:24,y:12,
  look:{shirt:"#4B7FB3",skin:"#C08356",hair:"#26202B",style:"afro"}},
 {name:{en:"Yola · Paletera",es:"Yola · Paletera"},world:"ex",x:17,y:0,
  look:{shirt:"#D77FA8",skin:"#E5AC82",hair:"#171219",style:"braids"}}
];
/* name eggs: lowercase triggers -> reaction lines (EN/ES in lockstep). dog:true eggs
   join as a lemon beagle critter instead of a person. All lines are ORIGINAL homage —
   in-world townsfolk reacting, never franchise quotes. Built 2026-08-30 from the
   reference research pack (Marvel / Harry Potter / Vampire Diaries / PLL). */
const EGGS={
 sonny:{triggers:["sonny"],dog:true,lines:{
  en:["A lemon beagle! The barrio has been waiting for this exact dog.","Sonny inspects the block. The block passes, barely.","Frederick has heard legends of a beagle with perfect vibes."],
  es:["¡Un beagle limón! El barrio esperaba justo a este perro.","Sonny inspecciona la cuadra. La cuadra aprueba, apenas.","Frederick ha oído leyendas de un beagle con vibra perfecta."]}},
 tony:{triggers:["tony","stark","iron man","ironman"],lines:{
  en:["Tony? Don Güero says even if you build a flying suit in a cave out of scrap, in this barrio you still need a permit.","Rosa put out a tip jar shaped like a red-and-gold helmet. Genius, billionaire... okay, mostly it's a very good tip jar.","The muralist painted a little glowing circle on the taquería sign. Now the al pastor feels self-funded."],
  es:["¿Tony? Don Güero dice que aunque armes un traje volador en una cueva con puro fierro viejo, en este barrio igual necesitas permiso.","Rosa puso un bote de propinas con forma de casco rojo y dorado. Genio, millonario... bueno, más que nada es muy buen bote.","El muralista pintó un circulito brillante en el letrero de la taquería. Ahora el pastor se siente autofinanciado."]}},
 loki:{triggers:["loki"],lines:{
  en:["Loki, eh? Chuy swears somebody keeps swapping the salsa labels. Small mischief, enormous consequences.","The paletera says any timeline where you skip dessert is the wrong timeline.","If a second trolley shows up looking exactly like the first one, do not board it. We've learned."],
  es:["¿Loki, eh? Chuy jura que alguien anda cambiando las etiquetas de las salsas. Travesura chiquita, consecuencias enormes.","La paletera dice que toda línea de tiempo donde te saltas el postre es la línea equivocada.","Si llega un segundo trolley idéntico al primero, no te subas. Ya aprendimos."]}},
 wanda:{triggers:["wanda","maximoff","scarlet witch"],lines:{
  en:["Wanda? The muralist once painted a whole block in red and called it 'everything that could have been.'","Doña Rosa says sadness is just love that lost its address, so she mails hers inside the tamales.","If the neighborhood suddenly looks like a 1950s TV show, go check on whoever is having a rough week."],
  es:["¿Wanda? El muralista una vez pintó toda una cuadra de rojo y lo llamó 'todo lo que pudo haber sido.'","Doña Rosa dice que la tristeza es amor que perdió su dirección, por eso ella manda la suya dentro de los tamales.","Si de repente el barrio parece programa de tele de los cincuenta, ve a ver quién anda pasando una semana difícil."]}},
 peter:{triggers:["peter","parker","spidey","spiderman","spider-man"],lines:{
  en:["Peter! Kike saw a kid backflip off the scaffolding to catch a falling ladder. Don Güero hired him on the spot.","The muralist says every hero in this barrio is somebody's neighbor first.","Big talents come with big chores, mijo. Start with the dishes."],
  es:["¡Peter! Kike vio a un chavo dar una maroma desde el andamio para atrapar una escalera. Don Güero lo contrató ahí mismo.","El muralista dice que todo héroe de este barrio primero es vecino de alguien.","Los grandes talentos traen grandes quehaceres, mijo. Empieza con los trastes."]}},
 thor:{triggers:["thor","odinson"],lines:{
  en:["Thor? Beto left his hammer on the lunch table and now nobody can 'lift' it. Nobody wants to work, that's why.","Mari says if lightning hits her crane one more time, she's charging the sky rent.","Chuy made a storm-grey pozole special. Thunder not included; seconds are."],
  es:["¿Thor? Beto dejó su martillo en la mesa del almuerzo y ahora nadie puede 'levantarlo'. Nadie quiere trabajar, por eso.","Mari dice que si un rayo le pega a su grúa otra vez, le va a cobrar renta al cielo.","Chuy hizo un pozole especial gris tormenta. Truenos no incluidos; el segundo plato sí."]}},
 steve:{triggers:["steve","rogers","cap","captain america"],lines:{
  en:["Steve, like the polite one with the shield? Around here the only unbreakable metal is Doña Rosa's comal. Nothing has ever dented it.","Lupe says real strength is filling out the permit forms correctly on the first try. He'd do it all week.","The viejitos at the domino table approve: old-fashioned manners, and he throws a frisbee with terrifying accuracy."],
  es:["¿Steve, como el educado del escudo? Aquí el único metal irrompible es el comal de Doña Rosa. Nada lo ha abollado jamás.","Lupe dice que la verdadera fuerza es llenar bien los formatos del permiso a la primera. Él lo haría toda la semana.","Los viejitos de la mesa de dominó lo aprueban: modales de antes, y tira el frisbee con una puntería que asusta."]}},
 natasha:{triggers:["natasha","romanoff","black widow"],lines:{
  en:["Natasha? The paletera says she settles every debt in her little notebook with free paletas. The red ones, obviously.","Xochi wants a jumpsuit that stylish AND that practical. Pockets, people. Pockets.","Nobody has ever seen her enter or leave the panadería, yet the conchas are always perfectly counted."],
  es:["¿Natasha? La paletera dice que salda cada deuda de su libretita con paletas gratis. Las rojas, obviamente.","Xochi quiere un traje así de elegante Y así de práctico. Bolsillos, señores. Bolsillos.","Nadie la ha visto jamás entrar ni salir de la panadería, y aun así las conchas siempre están perfectamente contadas."]}},
 groot:{triggers:["groot"],lines:{
  en:["He only ever says the one thing, but the jacaranda outside La Cocina leans in every time he says it.","The muralist gave the tree in his new mural exactly three words of dialogue. Budget cuts, he says.","Kike planted a stick from the construction site and waters it daily. 'Just in case,' he says."],
  es:["Solo dice una única cosa, pero la jacaranda afuera de La Cocina se inclina cada vez que la dice.","El muralista le dio al árbol de su mural nuevo exactamente tres palabras de diálogo. Recortes de presupuesto, dice.","Kike plantó una ramita de la obra y la riega a diario. 'Por si acaso,' dice."]}},
 lucky:{triggers:["lucky","pizza dog"],dog:true,lines:{
  en:["One eye, full heart, undefeated at catching a slice before it hits the floor.","The taquería opened a tab for him. He pays in loyalty and conveniently dropped napkins."],
  es:["Un ojo, todo el corazón, invicto atrapando rebanadas antes de que toquen el piso.","La taquería le abrió una cuenta. Paga con lealtad y servilletas convenientemente tiradas."]}},
 bruce:{triggers:["bruce","banner","hulk"],lines:{
  en:["Bruce? Chuy has a secret too: he's always hungry. That's the entire trick behind his tortas.","The trolley turns green when it gets angry... okay no, it's always green. But it IS always on time.","Don Güero says demolition day is basically therapy. Smash responsibly, and keep the helmet on."],
  es:["¿Bruce? Chuy también tiene un secreto: siempre tiene hambre. Ese es todo el truco de sus tortas.","El trolley se pone verde cuando se enoja... bueno no, siempre es verde. Pero eso sí, siempre llega a tiempo.","Don Güero dice que el día de demolición es básicamente terapia. Demuele con responsabilidad y no te quites el casco."]}},
 harry:{triggers:["harry","potter"],lines:{
  en:["A skinny kid with round glasses and a lightning mark on his forehead? I already painted him on the wall by the panaderia. People leave him pan dulce for luck.","He grew up in a closet under the stairs? Mija, that's just a studio apartment with worse marketing.","Chosen one, chosen schmosen. Around here nobody's special until Dona Rosa lets you salt the beans."],
  es:["Un flaquito de lentes redondos y una marca de rayo en la frente? Ya lo pinte en la barda junto a la panaderia. La gente le deja pan dulce para la suerte.","Que crecio en un closet bajo la escalera? Mija, eso es un depa de una pieza con mala publicidad.","Elegido, elegido... Aqui nadie es especial hasta que Dona Rosa te deja salarle los frijoles."]}},
 hermione:{triggers:["hermione","granger"],lines:{
  en:["She read the whole manual before touching the machine. In this economy? A hero.","Rumor says she attends two meetings at the same time. I've seen her calendar. I believe it.","Half her genius is books. The other half is raising her hand faster than doubt can catch her."],
  es:["Se leyo todo el manual antes de tocar la maquina. En estos tiempos? Una heroina.","Dicen que va a dos juntas al mismo tiempo. Yo vi su calendario. Le creo.","La mitad de su genio son los libros. La otra mitad es levantar la mano mas rapido que la duda."]}},
 ron:{triggers:["ron","weasley"],lines:{
  en:["Redheaded kid, six siblings, hand-me-down sweater? That's half my cousins. Good people.","He plays chess like it's life or death. At La Cocina we call that ordering for the whole table.","Terrified of spiders, loyal to the very end. Honestly? Same."],
  es:["Pelirrojo, seis hermanos y sueter heredado? Asi es la mitad de mis primos. Buena gente.","Juega ajedrez como si fuera de vida o muerte. En La Cocina a eso le decimos pedir para toda la mesa.","Le aterran las aranas y es leal hasta el final. La neta? Igual yo."]}},
 luna:{triggers:["luna","lovegood"],lines:{
  en:["She says there are invisible creatures floating around the construction site. Beto went to check. Now Beto says hi to them every morning.","She wears radish earrings and reads the magazine upside down. Honestly, the most reasonable person I know.","People call her odd. Odd is just early. Ask any muralist."],
  es:["Dice que hay criaturas invisibles flotando por la obra. Beto fue a revisar. Ahora Beto las saluda cada manana.","Trae aretes de rabano y lee la revista al reves. La neta, la persona mas razonable que conozco.","Le dicen rara. Lo raro nomas es lo que llega temprano. Preguntale a cualquier muralista."]}},
 dobby:{triggers:["dobby"],lines:{
  en:["The little guy works for free but cries with joy if you gift him a sock. I gave him one anyway. Best day of both our lives.","He kept apologizing to the dishes while washing them. Tovar signed him up for the wellness stipend immediately.","We got him unlimited vacation days. He still shows up at six a.m. Some habits take a generation to unlearn."],
  es:["El chaparrito trabaja gratis pero llora de gusto si le regalas un calcetin. Se lo di de todos modos. El mejor dia para los dos.","Les pedia perdon a los platos mientras los lavaba. Tovar lo inscribio al apoyo de bienestar de inmediato.","Le dimos vacaciones ilimitadas. Aun asi llega a las seis de la manana. Hay costumbres que tardan una generacion en quitarse."]}},
 hagrid:{triggers:["hagrid","rubeus"],lines:{
  en:["The big fella adopted a puppy from the pound. The pound says they have never seen that animal before. The pound sounds nervous.","He bakes cakes hard enough to pass inspection as bricks. Don Guero ordered forty for the retaining wall.","Every scary animal in the barrio has exactly one friend, and it's him."],
  es:["El grandote adopto un cachorrito de la perrera. La perrera dice que nunca habia visto ese animal. La perrera suena nerviosa.","Hornea pasteles tan duros que pasan la inspeccion como tabiques. Don Guero le encargo cuarenta para el muro de contencion.","Cada animal que da miedo en el barrio tiene exactamente un amigo, y es el."]}},
 hedwig:{triggers:["hedwig"],dog:true,lines:{
  en:["Fastest courier in the barrio. Finds you with no address, no app, and no tip screen.","White as a paleta de coco and twice as dignified.","Delivers your mail, then stares at you until you answer it. Better than any reminder app I've tried."],
  es:["La mensajera mas rapida del barrio. Te encuentra sin direccion, sin app y sin pantallita de propina.","Blanca como paleta de coco y el doble de digna.","Te entrega el correo y luego te mira fijo hasta que lo contestas. Mejor que cualquier app de recordatorios que he probado."]}},
 dumbledore:{triggers:["dumbledore","albus"],lines:{
  en:["An old man with a beard down to his belt who gives advice in riddles and loves lemon candy. So... my abuelo, but taller.","A good director tells you the truth slowly, in the order you can survive it. That takes a very long beard.","He'd win the whole strategy meeting and then compliment your socks on the way out. That's leadership."],
  es:["Un viejito con barba hasta el cinturon que da consejos en acertijos y ama los dulces de limon. O sea... mi abuelo, pero mas alto.","Un buen director te dice la verdad despacio, en el orden en que la aguantas. Para eso se necesita una barba muy larga.","Se ganaria toda la junta de estrategia y de salida te felicitaria por tus calcetines. Eso es liderazgo."]}},
 hogwarts:{triggers:["hogwarts","gryffindor","slytherin","hufflepuff","ravenclaw"],lines:{
  en:["We sorted the crew into four teams for the tamale cook-off. The sorting hat was a hard hat. It sang. Badly.","Brave, cunning, clever, or kind — around here we just watch which salsa you reach for first.","Every team swears the tower office is theirs by ancient right. That's why Lupe controls the permits."],
  es:["Dividimos a la cuadrilla en cuatro equipos para el concurso de tamales. El sombrero seleccionador era un casco. Canto. Feo.","Valiente, astuto, listo o buena gente: aqui nomas vemos que salsa agarras primero.","Cada equipo jura que la oficina de la torre es suya por derecho antiguo. Por eso Lupe controla los permisos."]}},
 elena:{triggers:["elena","gilbert"],lines:{
  en:["She sat at my counter writing in her journal for three hours. Ordered one horchata. Broke two hearts.","I swear I've seen her twin around here. Identical face. Worse attitude. Better heels.","Two brothers fighting over the same girl? At La Cocina we call that 'Tuesday.'"],
  es:["Se sentó en mi barra escribiendo en su diario tres horas. Pidió una horchata. Rompió dos corazones.","Te juro que he visto a su gemela por aquí. La misma cara. Peor actitud. Mejores tacones.","¿Dos hermanos peleando por la misma muchacha? En La Cocina a eso le decimos 'martes'."]}},
 damon:{triggers:["damon","salvatore"],lines:{
  en:["He bought one paleta, smirked like it was a crime, and a crow followed him home. I don't ask questions.","He gives everybody little nicknames so he doesn't have to learn names. Honestly? Efficient.","The bad-boy older brother act works right up until Doña Rosa tells you to bus your own table."],
  es:["Compró una paleta, sonrió de lado como si fuera un delito, y un cuervo lo siguió a su casa. Yo no pregunto.","Le pone apodos a todo el mundo para no aprenderse los nombres. ¿La verdad? Eficiente.","El numerito de hermano rebelde funciona hasta que Doña Rosa te manda a levantar tu mesa."]}},
 stefan:{triggers:["stefan"],lines:{
  en:["Very polite. Very broody. On some strict diet he won't explain. That forehead alone carries three seasons of drama.","He journals more than our whole book club. And we ARE a book club.","The responsible brother always gets the guilt AND the dishes. I've seen it a hundred times."],
  es:["Muy educado. Muy atormentado. Trae una dieta estricta que no explica. Esa frente carga sola tres temporadas de drama.","Escribe en su diario más que todo nuestro club de lectura. Y eso que SOMOS un club de lectura.","Al hermano responsable siempre le toca la culpa Y los trastes. Lo he visto cien veces."]}},
 bonnie:{triggers:["bonnie","bennett"],lines:{
  en:["Every time she walks by, my candles light themselves. I save so much on matches.","That girl saves everybody and gets a 'thanks' if she's lucky. Somebody get her a raise and a nap.","She bought all my dried herbs and said 'it's for a project.' The streetlights have been very well-behaved since."],
  es:["Cada vez que pasa, mis velas se prenden solitas. Ahorro un montón en cerillos.","Esa muchacha salva a todos y si acaso le dan las gracias. Que alguien le dé un aumento y una siesta.","Me compró todas las hierbas secas y dijo 'es para un proyecto'. Desde entonces los faroles se portan muy bien."]}},
 caroline:{triggers:["caroline","forbes"],lines:{
  en:["She planned the block party with a color-coded binder and a backup binder. The tamale line moved like clockwork.","Started out a little intense, ended up running the whole event. Some people just level up beautifully.","She reviewed my mural schedule with a spreadsheet. She was right. I hate that she was right."],
  es:["Organizó la fiesta de la cuadra con una carpeta con código de colores y una carpeta de respaldo. La fila de tamales avanzó como relojito.","Empezó medio intensa y terminó dirigiendo todo el evento. Hay gente que sube de nivel con estilo.","Me revisó el calendario del mural con una hoja de cálculo. Tenía razón. Me choca que tuviera razón."]}},
 katherine:{triggers:["katherine","pierce"],lines:{
  en:["Looks exactly like the sweet journal girl, except this one cut the line and complimented her own hair.","Five hundred years of running from her problems and she's never once missed a hair appointment. Respect. And fear.","She said 'I'm the fun one,' took my last mango paleta, and vanished. I've been telling this story for years."],
  es:["Es idéntica a la muchacha dulce del diario, solo que esta se metió en la fila y se echó piropos a sí misma.","Quinientos años huyendo de sus problemas y jamás ha fallado al salón. Respeto. Y miedo.","Dijo 'yo soy la divertida', se llevó mi última paleta de mango y desapareció. Llevo años contando esa historia."]}},
 alaric:{triggers:["alaric","saltzman"],lines:{
  en:["The night-school history teacher keeps 'losing' his crossbow in my toolshed. Don Güero says leave it, he tips well.","That man has survived more things than my abuela's molcajete. And that is a very old molcajete.","He teaches history like he was personally there for most of it. Attendance has never been better."],
  es:["Al maestro de historia de la nocturna se le sigue 'perdiendo' la ballesta en mi bodega. Don Güero dice que la dejemos, da buena propina.","Ese señor ha sobrevivido a más cosas que el molcajete de mi abuela. Y es un molcajete muy viejo.","Enseña historia como si le hubiera tocado vivir casi toda. La asistencia nunca había estado mejor."]}},
 klaus:{triggers:["klaus","mikaelson"],lines:{
  en:["Fancy accent, endless speeches about his thousand-year family drama, and then he paid for painting lessons for every kid on the block. Complicated guy.","He offered to paint our mural. Gorgeous work. Then he got offended that nobody bowed. Artists, right?","All that power, and what he really wants is his family at one dinner table. Señor, same."],
  es:["Acento elegante, puro discurso de su drama familiar de mil años, y luego les pagó clases de pintura a todos los niños de la cuadra. Un tipo complicado.","Se ofreció a pintar nuestro mural. Un trabajo precioso. Luego se ofendió porque nadie hizo reverencia. Artistas, ¿verdad?","Tanto poder, y lo que de verdad quiere es a su familia en una mesa cenando. Señor, igual yo."]}},
 mystic:{triggers:["mystic","mystic falls"],lines:{
  en:["A small town where every festival ends with somebody missing? Stressful. Our block parties just end with somebody's tío asleep on the trolley.","Founders' parties every month and nobody asks why the punch bowl has a lid? Not my town, gracias.","Every small town has its secrets. Ours is the mole recipe. Theirs is... quite a bit more."],
  es:["¿Un pueblito donde cada festival termina con alguien desaparecido? Qué estrés. Nuestras fiestas de cuadra terminan con el tío de alguien dormido en el trolley.","¿Fiestas de fundadores cada mes y nadie pregunta por qué la ponchera tiene tapa? No es mi pueblo, gracias.","Todo pueblito tiene sus secretos. El nuestro es la receta del mole. El de ellos es... bastante más."]}},
 spencer:{triggers:["spencer"],lines:{
  en:["Spencer already color-coded the taco truck menu. By salsa heat AND alphabetically.","She drinks her café de olla like it's a competitive sport. Honestly? She's winning.","I asked her for the time and she gave me a timeline. With suspects."],
  es:["Spencer ya organizó el menú del camión de tacos por colores. Por picor de salsa Y en orden alfabético.","Se toma su café de olla como si fuera deporte de competencia. ¿La verdad? Va ganando.","Le pedí la hora y me dio una línea de tiempo. Con sospechosos."]}},
 aria:{triggers:["aria"],lines:{
  en:["Aria bought one earring from every stand at the mercadito. Somehow the look works.","She's writing a short story about the trolley. The trolley seems nervous.","Pink streak in her hair, poetry in her tote bag. The muralist calls her a walking mood board."],
  es:["Aria compró un arete de cada puesto del mercadito. Y de algún modo el look funciona.","Está escribiendo un cuento sobre el trolley. El trolley anda nervioso.","Mechón rosa en el pelo, poesía en la bolsa. La muralista dice que es un mood board andante."]}},
 hanna:{triggers:["hanna","hannah"],lines:{
  en:["Hanna rated everyone's outfits at the block party. I got a seven. Best day of my week.","She says a quinceañera dress is just couture with better music. Can't argue with that.","Half her advice makes no sense and all of it works. It's a gift."],
  es:["Hanna calificó los outfits de todos en la fiesta de la cuadra. Me dio un siete. El mejor día de mi semana.","Dice que un vestido de quince años es alta costura con mejor música. No se puede discutir.","La mitad de sus consejos no tienen sentido y todos funcionan. Es un don."]}},
 emily:{triggers:["emily"],lines:{
  en:["Emily swam the whole coastline before breakfast. The pelicans are starting a fan club.","Sweetest one at the taco shop, fastest one in the water. Pick a lane? She picked all of them.","She's teaching the rec center kids to swim. Now they all want goggles for their birthdays."],
  es:["Emily nadó toda la costa antes del desayuno. Los pelícanos ya quieren fundar su club de fans.","La más linda en la taquería, la más rápida en el agua. ¿Que escoja un carril? Los escogió todos.","Les está enseñando a nadar a los niños del centro. Ahora todos quieren goggles de cumpleaños."]}},
 alison:{triggers:["alison","ali"],lines:{
  en:["Alison's back? Half the barrio has a story about her, and none of the stories match.","She smiled at me like she knows where I hide the good pan dulce. Nobody knows that.","Ali could talk the paletera out of her last coco paleta. And the paletera would say thank you."],
  es:["¿Volvió Alison? Medio barrio tiene una historia de ella, y ninguna coincide.","Me sonrió como si supiera dónde escondo el buen pan dulce. Nadie sabe eso.","Ali convencería a la paletera de darle su última paleta de coco. Y la paletera le daría las gracias."]}},
 mona:{triggers:["mona"],lines:{
  en:["Mona turned the loyalty punch cards into a spreadsheet. She's three punches ahead of everyone.","One summer she showed up with new glasses and a plan. We're still catching up.","Don't play lotería against Mona. She knows the whole deck AND your tells."],
  es:["Mona pasó las tarjetas de sellos a una hoja de cálculo. Va tres sellos adelante de todos.","Un verano llegó con lentes nuevos y un plan. Todavía no la alcanzamos.","No juegues lotería contra Mona. Se sabe toda la baraja Y tus gestos."]}},
 toby:{triggers:["toby"],lines:{
  en:["Don Güero hired Toby on the spot. Quiet guy, but his miter cuts could make you cry.","He built Doña Rosa a spice shelf without being asked. The barrio has officially adopted him.","Strong, silent, sands everything twice. The crew calls him the telenovela carpenter."],
  es:["Don Güero contrató a Toby al instante. Callado, pero sus cortes a inglete te hacen llorar.","Le hizo un estante de especias a Doña Rosa sin que nadie se lo pidiera. El barrio ya lo adoptó oficialmente.","Fuerte, callado, y todo lo lija dos veces. La cuadrilla le dice el carpintero de telenovela."]}},
 caleb:{triggers:["caleb"],lines:{
  en:["Caleb fixed the taco shop's wifi from a moving trolley. Didn't even look up.","He turned an old laptop into a jukebox for La Cocina. Doña Rosa pays him in tamales now.","If your phone starts acting haunted, take it to Caleb. He un-haunts them."],
  es:["Caleb arregló el wifi de la taquería desde el trolley en marcha. Ni levantó la vista.","Convirtió una laptop vieja en rocola para La Cocina. Doña Rosa ya le paga con tamales.","Si tu teléfono empieza a andar embrujado, llévaselo a Caleb. Él los desembruja."]}},
 rosewood:{triggers:["rosewood"],lines:{
  en:["This barrio is like Rosewood but with better tacos and fewer secrets. Okay, the same amount of secrets.","Small town rules: everybody knows your business before you do."],
  es:["Este barrio es como Rosewood pero con mejores tacos y menos secretos. Bueno, los mismos secretos.","Reglas de pueblo chico: todos saben tus asuntos antes que tú."]}},
 pepe:{triggers:["pepe"],dog:true,lines:{
  en:["Woof! (He guards two things: secrets and dropped tacos. Mostly dropped tacos.)","This little guy has never sent a mysterious text in his life. We checked."],
  es:["¡Guau! (Cuida dos cosas: secretos y tacos caídos. Más que nada tacos caídos.)","Este chiquito jamás ha mandado un mensaje misterioso. Lo comprobamos."]}}
};
/* ambient nerd chatter: mixed into every chill townsperson's rotation (EN/ES in lockstep) */
const CHATTER={
 en:["Half the barrio vanished into a matinée last night. The other half is dodging spoilers like potholes.","The muralist keeps painting people landing on one knee with a fist down. Says knees like that deserve a mural, not an ambulance.","Snap your fingers all you want; the only thing disappearing around here is the last tamal.","Doña Rosa says every good origin story starts in somebody's kitchen.","Six shiny little stones on one glove and suddenly everyone in the plaza is a jeweler with opinions.","The kids chalked a whole shared universe on the sidewalk. Phase four starts by the fire hydrant.","The trolley schedule lists a stop between 9 and 10 that nobody can ever find. Some kids swear they've boarded there.","La Cocina is testing a warm butterscotch soda that foams like it knows something. Two refills and you start believing in magic.","Kike swears his level is a magic wand. It's a level, Kike. But fine — the walls do come out straight.","Mail delivered by owl sounds romantic until one drops a jury summons in your caldo.","Xochi painted a door on the mural so convincing that pigeons keep knocking. Nobody has the heart to tell them it's a wall.","Somewhere out there is a castle school where the staircases move. Here the trolley moves and the schedule doesn't. Same energy.","A crow has been watching the taco line all week. Either it wants al pastor or it's somebody's dramatic pet.","New rule at La Cocina: we're happy to invite you in, but you do have to actually order something.","Doña Rosa planted verbena by the door. Says it keeps away mosquitoes and 'certain customers.'","Suddenly everybody around here keeps a journal. Whatever they're putting in the horchata, don't stop.","The new guy only walks on the shady side of the street. Huge ring, strong opinions on sunscreen. We don't judge.","Two brothers just opened a shop together on Fifth. Give it a week.","Got a text from a number I don't know. It just said 'nice haircut.' ...Thank you?","Four friends walked by in matching sunglasses like they share one enormous secret. I want in.","Someone signed the panadería guest book with a single letter. Dramatic. Loved it.","In this barrio a secret lasts about as long as a warm concha. So, four minutes.","My group chat has more plot twists than a telenovela. And better snacks.","The muralist painted a big eye by the trolley stop. I say hi to it every morning. Just in case."],
 es:["Medio barrio desapareció anoche en una función. La otra mitad esquiva los spoilers como baches.","El muralista sigue pintando gente aterrizando en una rodilla con el puño abajo. Dice que esas rodillas merecen mural, no ambulancia.","Truena los dedos todo lo que quieras; aquí lo único que desaparece es el último tamal.","Doña Rosa dice que toda buena historia de origen empieza en la cocina de alguien.","Seis piedritas brillantes en un guante y de repente todos en la plaza son joyeros con opiniones.","Los niños dibujaron con gis todo un universo compartido en la banqueta. La fase cuatro empieza junto al hidrante.","El horario del trolley marca una parada entre la 9 y la 10 que nadie encuentra nunca. Unos ninos juran que ahi se han subido.","En La Cocina estan probando un refresco tibio de caramelo que hace espuma como si supiera algo. Dos refills y empiezas a creer en la magia.","Kike jura que su nivel es una varita magica. Es un nivel, Kike. Pero bueno... las paredes si salen derechas.","El correo por buho suena romantico hasta que uno te suelta un citatorio en el caldo.","Xochi pinto una puerta tan convincente en el mural que las palomas siguen tocando. Nadie tiene corazon para decirles que es pared.","En algun lugar hay una escuela en un castillo donde las escaleras se mueven. Aqui se mueve el trolley y el horario no. La misma energia.","Un cuervo lleva toda la semana vigilando la fila de tacos. O quiere al pastor o es la mascota dramática de alguien.","Regla nueva en La Cocina: con gusto te invitamos a pasar, pero sí tienes que pedir algo.","Doña Rosa plantó verbena junto a la puerta. Dice que espanta a los moscos y a 'ciertos clientes'.","De repente todos por aquí llevan un diario. Lo que sea que le pongan a la horchata, que no le paren.","El nuevo solo camina por la sombrita. Anillo enorme, opiniones fuertes sobre el bloqueador. No juzgamos.","Dos hermanos acaban de abrir un negocio juntos en la Quinta. Dale una semana.","Me llegó un mensaje de un número desconocido. Solo decía 'bonito corte.' ...¿Gracias?","Pasaron cuatro amigas con lentes iguales, como si compartieran un secreto enorme. Yo quiero entrar.","Alguien firmó el libro de visitas de la panadería con una sola letra. Dramático. Me encantó.","En este barrio un secreto dura lo que una concha calientita. O sea, cuatro minutos.","Mi chat del grupo tiene más giros que una telenovela. Y mejores botanas.","La muralista pintó un ojo grande junto a la parada del trolley. Lo saludo cada mañana. Por si acaso."]
};
