/* Meridian Quest content pack — quests, English. Mirror every change in quests.es.js. */
/* Frederick's secret side quest (not part of the 10) */
const FQEN={npc:"fred",title:"🐾 Personal side quest: Frederick's Files",start:"a",nodes:{
 a:{say:"Frederick drops a chewed folder at your feet. Inside: vet reminders on napkins, a feeding schedule that lives in three people's heads, and 40 unposted photos of him being majestic. This dog needs an ops system.",
    codex:"Personal ops is PM discipline with smaller stakes: one source of truth, recurring reminders for anything on a cycle (food, vet, grooming), and one list everyone shares. If it repeats, it gets a reminder — memory is not a system.",
    q:"How do you organize Frederick's life?",
    ch:[{t:"One giant sticky note on the fridge",out:{r:"mid",concept:"Single source of truth",why:"It IS one source of truth — but nothing reminds anyone of anything, and the vet appointment dies the day someone needs the fridge. Half credit.",beat:"Frederick sniffs the sticky note. Unimpressed."}},
        {t:"A shared calendar with recurring reminders + one shared checklist",next:"b"},
        {t:"Hire a dog assistant",out:{r:"bad",concept:"Single source of truth",why:"An assistant for a dog's calendar is a payroll line for a problem two recurring reminders solve.",beat:"Marcus appears from nowhere. “A WHAT for the dog?”"}}]},
 b:{say:"His public awaits. Forty majestic photos, zero posts. Frederick's content pipeline?",
    codex:"Creative work batches: one session producing a month of content beats posting when you remember. AI drafts the captions; a human approves before anything goes out — Frederick cannot approve, he is a dog.",
    q:"The content plan is…",
    ch:[{t:"Post whenever you remember",out:{r:"mid",concept:"Batching & scheduling",why:"That's how it's going now — 40 photos, zero posts. Sporadic effort loses to a boring schedule every time. Half credit for honesty.",beat:"Frederick's fans refresh in vain."}},
        {t:"Monthly batch day: AI drafts captions, you approve, a scheduler posts",out:{r:"ok",concept:"Batching & scheduling",why:"One hour a month, AI does the writing, human keeps the judgment, the scheduler does the remembering. Frederick's brand: consistent.",beat:"First scheduled post hits 200 likes. Frederick remains humble."}},
        {t:"Let AI auto-post as Frederick, unsupervised",out:{r:"bad",concept:"Batching & scheduling",why:"Unsupervised auto-posting is how brands die. No review, no floor.",beat:"Within the hour, Frederick's account endorses a crypto scheme."}}]}}};
const QEN=[
 {npc:"tovar",title:"The 500-doc chatbot",start:"a",nodes:{
  a:{say:"Store managers call me all day with policy questions. I want a chatbot on these 500 docs — and corporate rewrites them every month.",
     codex:"Two ways to give a model knowledge: train it into the model itself (slow, costly, frozen once done) — or keep it in a searchable index the model reads at answer time, fresh the moment a doc updates.",
     q:"The docs change monthly. Where does the knowledge live?",
     ch:[{t:"Train a custom model on the docs",out:{r:"bad",concept:"RAG vs fine-tuning",why:"Monthly retraining chases stale docs with money. By the time training finishes, corporate has rewritten the manual.",beat:"Priya, quietly: “That's how we lost the last lead.”"}},
         {t:"Index the docs; the bot retrieves the right pages per question",next:"b"},
         {t:"Paste all 500 docs into every prompt",out:{r:"bad",concept:"RAG vs fine-tuning",why:"You'd pay for 500 documents on every single question — and models lose focus across enormous inputs anyway.",beat:"Marcus materializes holding a calculator. Ominously."}}]},
  b:{say:"Indexing — good. One more thing: yesterday a manager asked about a policy that isn't in any document at all. What should the bot do?",
     codex:"A grounded bot answers only from retrieved text. When retrieval comes back empty, the honest moves are admitting it or routing to a human — the dangerous move is letting the model improvise.",
     q:"No matching document exists. The bot should…",
     ch:[{t:"Answer anyway from general knowledge — it usually sounds right",out:{r:"bad",concept:"Grounding & refusal",why:"“Sounds right” is how Free Churro Friday happens. An ungated answer with no source is a hallucination waiting for a customer.",beat:"Camila, from three desks away: “Don't you dare.”"}},
         {t:"Say “I don't have that policy” and route the question to the ops team",out:{r:"ok",concept:"Grounding & refusal",why:"A grounded bot that admits the gap — and hands a human the question — builds trust and shows ops which docs are missing.",beat:"The ops director nods slowly. “The bot knows what it doesn't know. Unlike my nephew.”"}},
         {t:"Make the bot apologize and end the chat",out:{r:"mid",concept:"Grounding & refusal",why:"Safe, but a dead end — no human routing means the manager's real question dies in the chat. Half credit: nothing false, nothing helpful.",beat:"Shipped with incidents. The manager calls the ops director anyway."}}]}}},
 {npc:"camila",title:"Free Churro Friday",start:"a",nodes:{
  a:{say:"The pilot bot just promised a manager ‘Free Churro Friday — all locations.’ That policy does not exist. Managers are already asking about it.",
     codex:"Models generate plausible text — when they don't know, plausible means invented. Asking nicely or lowering randomness reduces variety, not fabrication. What works: answers may only come from retrieved documents, with a citation.",
     q:"How do you kill the imaginary churros?",
     ch:[{t:"Add “don't make things up” to the instructions",out:{r:"mid",concept:"Hallucination control",why:"It helps at the margins — and fails the day it matters. Instructions nudge; they don't gate. Half credit for trying the cheap fix first.",beat:"The bot invents ‘Taco Tuesday Amnesty’ a week later."}},
         {t:"Set randomness to zero",out:{r:"bad",concept:"Hallucination control",why:"Temperature zero makes the bot confidently wrong the same way every time. Determinism isn't truth.",beat:"Camila: “Now it promises churros CONSISTENTLY.”"}},
         {t:"Ground every answer in retrieved text — no source, no answer",out:{r:"ok",concept:"Hallucination control",why:"Grounding treats the cause: the bot states only what a real document says, cites it, or admits it doesn't have the policy.",beat:"Camila drafts the official Death of Churro Friday memo. There is grief."}}]}}},
 {npc:"legal",title:"The 300-page contract",start:"a",nodes:{
  a:{say:"I need Q&A over the 300-page franchise agreement. The prototype nails page 20 and faceplants on page 200.",
     codex:"Every request has a token budget — you pay for every word sent, every time — and models attend unevenly across very long inputs: the middle sags. Less, better-chosen text beats everything-and-hope.",
     q:"How do you cover all 300 pages?",
     ch:[{t:"Chunk the contract; retrieve only sections relevant to each question",out:{r:"ok",concept:"Context windows & chunking",why:"Retrieval sends the three pages that matter instead of billing legal for all 300 every time — and quality holds on page 200 like it does on page 20.",beat:"Dana closes her laptop satisfied, which legal-ly speaking is a hug."}},
         {t:"Query a one-time summary instead",out:{r:"mid",concept:"Context windows & chunking",why:"Works for “what's the gist” — fails the clause-level questions contracts exist for. Half credit: fine as a companion, wrong as the answer.",beat:"Dana: “The summary says ‘standard terms apply.’ WHICH terms, bot?”"}},
         {t:"Buy a giant context window and send all 300 pages every time",out:{r:"bad",concept:"Context windows & chunking",why:"The middle still sags, and now every parking question costs a full contract's worth of tokens.",beat:"Marcus appears. He heard the word ‘buy.’"}}]}}},
 {npc:"marcus",title:"The morning report",start:"a",nodes:{
  a:{say:"Someone spends 40 minutes every morning pulling sales numbers, formatting the report, emailing leadership. Can your… robot… handle it?",
     codex:"A plain model call only writes text — it can't touch a database or send email. Hand it tools (run query, send email) and it can decide which tool, in what order: that's an agent. Fixed steps live in code; judgment lives in the model.",
     q:"How does the morning report automate?",
     ch:[{t:"One giant ‘do the report’ prompt",out:{r:"bad",concept:"Agents & tool use",why:"A beautiful report full of imaginary numbers — no tools, no data access, pure fiction in a spreadsheet costume.",beat:"Leadership compliments the formatting. Then reads the numbers."}},
         {t:"An agent with tools: query → format → send",out:{r:"ok",concept:"Agents & tool use",why:"Real data through real tools, orchestrated by the model. Forty minutes becomes zero.",beat:"Marcus: “If the robot breaks, it's coming out of your budget.” He's smiling. Probably."}},
         {t:"Tell Marcus robots aren't ready",out:{r:"bad",concept:"Agents & tool use",why:"They've been ready. The CFO asking you for automation is not the person to underdeliver to.",beat:"Marcus writes something in a small notebook. You don't like the notebook."}}]}}},
 {npc:"marcus",title:"The invoice",start:"a",nodes:{
  a:{say:"This invoice. Ten thousand support tickets a month, all answered by the most expensive model money can buy. Most of them ask where their order is.",
     codex:"Models come in sizes and prices; small ones do simple work for pennies. Systems can flag their own low-confidence answers — so easy tickets go cheap, and only hard ones escalate to the flagship.",
     q:"How do you cut the bill without cutting quality?",
     ch:[{t:"Everything to the cheapest model, accept the drop",out:{r:"mid",concept:"Model routing & cost design",why:"The bill collapses — and so does quality exactly on the hard tickets that decide whether customers stay. Half credit: right instinct, no escape hatch.",beat:"Refund disputes now answered by a model that thinks a churro is a shoe."}},
         {t:"Cheap model first; escalate hard or unsure tickets to premium",out:{r:"ok",concept:"Model routing & cost design",why:"The cheap model earns its keep on “where's my order”; the flagship earns its price on the gnarly 10%. Same quality where it matters, fraction of the spend.",beat:"Marcus initials the invoice. From Marcus, that's fireworks."}},
         {t:"Ask the vendor for a discount",out:{r:"bad",concept:"Model routing & cost design",why:"A discount on the wrong architecture is still the wrong architecture, now with a longer contract.",beat:"The vendor sends a fruit basket. Marcus sends it back."}}]}}},
 {npc:"priya",title:"The 98% quote-bot",start:"a",nodes:{
  a:{say:"Quote-bot is 98% right and auto-sends everything. Here's the other 2% — real customers, prices that lose real money. Sales loves it. Finance found the 2%.",
     codex:"Automation level should match cost-of-error: full auto where mistakes are cheap, human review where they're expensive. Confidence scores sort which is which — only the uncertain outputs wait for a person.",
     q:"Ship it, gate it, or kill it?",
     ch:[{t:"Ship — 98% is an A+",out:{r:"bad",concept:"Human-in-the-loop",why:"98% is an A+ on a quiz. On auto-sent pricing it's 200 wrong quotes a month, in dollars.",beat:"Finance starts a spreadsheet titled ‘The 2%.’ It has your name on it."}},
         {t:"Route uncertain quotes to human review",next:"b"},
         {t:"Kill it until perfect",out:{r:"bad",concept:"Human-in-the-loop",why:"Perfect never comes, and you just threw away the 98% that was printing time savings.",beat:"Sales holds a small vigil."}}]},
  b:{say:"Agreed — review queue. Now the tree question: WHICH quotes wait for a human?",
     codex:"Reviewing everything recreates the manual job you automated. Reviewing nothing is where you started. The lever is the confidence threshold — plus the cost of the error type: a too-low price hurts more than a too-slow quote.",
     q:"What goes to the review queue?",
     ch:[{t:"Every quote — humans re-check all of it",out:{r:"mid",concept:"Confidence thresholds",why:"Safe but self-defeating: you've rebuilt the 40-hour job with extra steps. Half credit — no losses, no leverage.",beat:"The reviewer now reviews quotes about reviewing."}},
         {t:"Only low-confidence quotes and any quote above a price ceiling",out:{r:"ok",concept:"Confidence thresholds",why:"Confidence catches the model's own doubt; the price ceiling catches the expensive mistakes it's confidently wrong about. Two nets, minimal drag.",beat:"Sales keeps its speed, finance keeps its sleep, Priya almost smiles."}},
         {t:"A random 10% sample",out:{r:"mid",concept:"Confidence thresholds",why:"Sampling measures error rate — it doesn't stop errors. Fine for monitoring, wrong as the only gate. Half credit.",beat:"The 2% waves at you from the un-sampled 90%."}}]}}},
 {npc:"cto",title:"Bayview's notes",start:"a",nodes:{
  a:{say:"Our doctors drown in paperwork. I want AI summaries of visit notes — but every note is full of patient data, and I need to not end up in the news.",
     codex:"Health data is regulated. Two keys make LLM work possible: mask patient identifiers before the model sees text, and use an enterprise endpoint covered by a signed agreement (BAA) that permits health data. Consumer AI endpoints are never covered.",
     q:"How do you deliver the summaries?",
     ch:[{t:"Send raw notes to a consumer AI tool",out:{r:"bad",concept:"PII/PHI governance",why:"That's the career-ending option — a reportable breach with a timestamp.",beat:"Somewhere, a compliance officer wakes in a cold sweat, unsure why."}},
         {t:"Mask identifiers + BAA-covered endpoint + log everything",out:{r:"ok",concept:"PII/PHI governance",why:"The model sees only what it needs, on infrastructure that's allowed to see it, with an audit trail. The standard, defensible path.",beat:"Dr. Okafor: “Finally. Someone who's done this in healthcare before.”"}},
         {t:"Refuse: AI can't touch health data",out:{r:"mid",concept:"PII/PHI governance",why:"Zero risk, zero help — and someone less careful will say yes instead. Half credit for caution without craft.",beat:"The doctors keep drowning, but compliantly."}}]}}},
 {npc:"junior",title:"Theo's prompt",start:"a",nodes:{
  a:{say:"I reworded the support bot's prompt and the demo got WAY better! Can we ship today? Please? I already told my mom.",
     codex:"One good demo is an anecdote. Prompt changes routinely fix one case and silently break five others. Teams keep an eval set — real past cases with known good answers — and score every change against it before shipping. Unit tests, but for AI.",
     q:"Does Theo's prompt ship today?",
     ch:[{t:"Ship it — you both saw it improve",out:{r:"bad",concept:"Evals & regression testing",why:"The demo showed one case. The eval would have shown the two refund flows it broke. Now customers get to find them.",beat:"Theo's mom is proud. The refund queue is not."}},
         {t:"Run the eval set; ship tomorrow if the score holds",out:{r:"ok",concept:"Evals & regression testing",why:"One hour of eval catches what demos hide — it finds two broken refund cases. Theo ships tomorrow, correctly, and learns the ritual.",beat:"Theo buys Priya coffee for a week. Growth arc initiated."}},
         {t:"Ask another AI which prompt is better",out:{r:"mid",concept:"Evals & regression testing",why:"AI-as-judge is a real technique — inside an eval harness with defined criteria. As a vibes oracle, it's a coin with opinions. Half credit.",beat:"The judge model says both prompts are “great!” It says that about everything."}}]}}},
 {npc:"tovar",title:"The laminated plan",start:"a",nodes:{
  a:{say:"One more thing — managers want meeting transcription inside the app. Theo has a six-month plan to build speech-to-text from scratch. He laminated it.",
     codex:"Some AI capabilities are commodities — transcription, translation, OCR — sold as excellent APIs for cents. Differentiation lives in what your product does with the output, not in rebuilding the commodity.",
     q:"Six months to build, or…?",
     ch:[{t:"Build speech-to-text from scratch",out:{r:"bad",concept:"Build vs buy",why:"Six months rebuilding what costs cents per minute, to reach quality the API already beats. Nobody will notice — except Marcus.",beat:"The lamination was the best part of the plan."}},
         {t:"Integrate a proven transcription API; build the features on top",out:{r:"ok",concept:"Build vs buy",why:"Two weeks to integrate, then the team builds what managers actually asked for — the stuff on top of the transcript. Build the last mile, buy the commodity.",beat:"Theo un-laminates the plan. Quietly."}},
         {t:"Hire human transcribers",out:{r:"bad",concept:"Build vs buy",why:"Slower, costlier, and doesn't scale past the third meeting. It's 2026.",beat:"The job posting gets three applicants. All bots."}}]}}},
 {npc:"ceo",title:"The 8-second silence",start:"a",nodes:{
  a:{say:"Final demo. Your phone agent gives brilliant answers… eight seconds after callers stop talking. I counted. Twice. Callers hang up.",
     codex:"In real-time AI, people judge time-to-first-word, not time-to-full-answer. Two levers: stream the reply so speech starts as it generates, and open with a small fast model while heavier reasoning catches up behind it.",
     q:"Kill the eight-second silence:",
     ch:[{t:"Wait for faster hardware",out:{r:"bad",concept:"Latency engineering",why:"Latency is a design problem you can fix this sprint, not a hardware problem someone else fixes next year.",beat:"The CEO checks his watch a third time. It echoes."}},
         {t:"Stream the reply; lead with a small fast model",next:"b"},
         {t:"Add hold music",out:{r:"bad",concept:"Latency engineering",why:"Now it's eight seconds of jazz before the disappointment.",beat:"Camila vetoes the smooth-jazz license request."}}]},
  b:{say:"Priya, patching it live: “Streaming's in. Last call — what's the metric on the launch dashboard?”",
     codex:"You get what you measure. Total answer time hides the fix; time-to-first-word is what callers actually feel — with total time and answer quality tracked beside it, not instead of it.",
     q:"The headline latency metric is…",
     ch:[{t:"Average total response time",out:{r:"mid",concept:"Latency metrics",why:"Real but wrong headline — a slow-but-streaming answer FEELS instant, and this metric can't see that. Half credit; keep it secondary.",beat:"The dashboard says ‘slower.’ The callers say ‘finally.’"}},
         {t:"Time-to-first-word",out:{r:"ok",concept:"Latency metrics",why:"That's the moment the silence ends — the thing callers judge. Track total time and quality beside it, headline this.",beat:"Sub-second. The CEO puts his watch away. Priya smiles. Witnesses confirm."}},
         {t:"Number of callers who hang up",out:{r:"mid",concept:"Latency metrics",why:"A great outcome metric — but it's a lagging alarm, not a steering wheel. Half credit.",beat:"“Good news: hang-ups down. Bad news: we learned it a week late.”"}}]}}},
 {npc:"rosa",title:"The phone never stops",start:"a",nodes:{
  a:{say:"Mijo, the phone rings all day — orders, questions, “¿tienen birria?” I miss half the calls while I'm cooking. They tell me a robot can answer. Fine. But can it take orders WITHOUT ruining them?",
     codex:"A voice agent can take phone orders — the trick is structure. Speech gets matched into a structured order (items, sizes, extras, price) against the real menu, then read back to the caller to confirm before it counts. Free-text guessing is how you end up with three surprise birrias.",
     q:"How should the phone agent take orders?",
     ch:[{t:"Let it chat freely and write down what it hears",out:{r:"bad",concept:"Structured outputs",why:"Free text means “large horchata” becomes “¿la orchata grande?” becomes mystery tickets. No structure, no reliable kitchen ticket.",beat:"Ticket #4 reads “birria??? maybe 3?”. The kitchen weeps."}},
         {t:"Match every order to the real menu as structured items, then read it back to confirm",next:"b"},
         {t:"Keep missing calls — it's more authentic",out:{r:"bad",concept:"Structured outputs",why:"Missed calls are missed revenue — a third of Rosa's orders come by phone.",beat:"Across town, a competitor's robot says “gracias por su orden.”"}},
         {t:"Hire someone just to answer the phone",out:{r:"mid",concept:"Structured outputs",why:"A human works — at a salary, with breaks, quitting at the worst moment. A real option, a heavy cost for a solvable problem. Half credit.",beat:"The new hire quits after one Saturday rush."}}]},
  b:{say:"It works, mijo! But last night someone asked for “the wedding catering package for 200 people” — and the robot happily said YES. We do not do weddings.",
     codex:"Agents need explicit guardrails: what they may sell, ceilings on order size, and a rule that unusual requests get handed to a human. Confirmation protects the customer; guardrails protect Rosa.",
     q:"Fix the robot's enthusiasm:",
     ch:[{t:"Menu-only + a max order size + route anything unusual to Rosa's phone",out:{r:"ok",concept:"Agent guardrails",why:"Sell only what exists, up to sane limits, and escalate the weird stuff to a human. Rosa decides about weddings — not the robot.",beat:"The robot politely transfers a quinceañera inquiry. Rosa negotiates like a champion."}},
         {t:"Turn the robot off at night",out:{r:"mid",concept:"Agent guardrails",why:"That dodges the failure by dodging the revenue. Half credit — safe, but small.",beat:"The night owls order pizza instead. Traitors."}},
         {t:"Let it improvise — the customer is always right",out:{r:"bad",concept:"Agent guardrails",why:"An agent without limits will promise 200 birrias and a mariachi. The cost of error is unbounded.",beat:"Somewhere, Marcus feels a disturbance he cannot explain."}},
         {t:"Make the robot upsell everything to boost revenue",out:{r:"bad",concept:"Agent guardrails",why:"An agent optimizing revenue without limits torches trust — what it may OFFER is a guardrail decision too.",beat:"An abuelita ordering one coffee gets offered the party platter. Twice."}}]}}},
 {npc:"chuy",title:"Prep for Friday",start:"a",nodes:{
  a:{say:"Every Friday I guess how much barbacoa to prep. Guess low — we run out by 8pm and people cry. Guess high — Sunday me eats sad leftovers for three days. There has to be a better way, ¿no?",
     codex:"Forecasting beats gut feeling: average the last several Fridays, adjust for what's different this week (payday, weather, events), and track how wrong you were to improve each week. Overproduction is money in the trash; running out is customers in the trash.",
     q:"How much barbacoa for Friday?",
     ch:[{t:"Same as always — feel it out",out:{r:"mid",concept:"Demand forecasting",why:"The gut got Chuy this far — sometimes right, never measured, impossible to improve. Half credit for surviving on instinct.",beat:"Friday, 8:15pm: “no hay.” Hearts break audibly."}},
         {t:"Average the last 8 Fridays, adjust for payday and weather, track the error weekly",out:{r:"ok",concept:"Demand forecasting",why:"A simple forecast plus error tracking gets smarter every single week. This is data science in an apron.",beat:"Chuy tapes the forecast to the walk-in. It becomes law."}},
         {t:"Double everything and sell leftovers Saturday",out:{r:"bad",concept:"Demand forecasting",why:"Waste as a strategy — the margin dies quietly in the walk-in fridge.",beat:"A tower of Sunday barbacoa. Even Frederick, visiting, declines."}},
         {t:"Buy a big AI forecasting platform first",out:{r:"mid",concept:"Demand forecasting",why:"Tools before data discipline is backwards — the simple average with error tracking wins until the data earns a platform. Half credit.",beat:"The platform's onboarding call runs longer than Friday service."}}]}}},
 {npc:"guero",title:"The estimate",start:"a",nodes:{
  a:{say:"Jefe! A client wants a remodel quote for a storefront across town. She sent thirty photos and wants the number TODAY. Old days, I'd drive over, measure for two hours, and guess the rest. You're the AI person — impress me.",
     codex:"Vision models can read measurements from photos: wall areas, fixtures, damage, materials. The reliable pattern is AI-drafted line items from the photos — quantities, materials, labor — with a human checking prices and the weird corners before it goes out. Fast AND defensible.",
     q:"How does the quote get built?",
     ch:[{t:"Eyeball the photos and quote from experience",out:{r:"mid",concept:"Vision estimates",why:"Experience is real — but unmeasured guesses win jobs that lose money. Half credit for the gray hairs.",beat:"Don Güero's mustache twitches. He knows you're right."}},
         {t:"AI drafts a line-item estimate from the photos; Güero verifies materials and prices before it ships",next:"b"},
         {t:"Promise to beat any other quote, figure it out later",out:{r:"bad",concept:"Vision estimates",why:"Winning on price without knowing your costs is how construction companies die with full calendars.",beat:"Lupe, without looking up: “That's how the last company went down.”"}},
         {t:"Send an apprentice to measure everything by hand today",out:{r:"mid",concept:"Vision estimates",why:"Accurate — and slow. The quote lands late, and late quotes lose. Half credit for rigor without speed.",beat:"The apprentice measures beautifully. The client signed elsewhere at noon."}}]},
  b:{say:"We won the job, jefe! But now the client says: “while you're at it, just add one little bathroom.” ONE LITTLE BATHROOM. What do I tell her?",
     codex:"Scope changes are where jobs bleed. The discipline is the change order: every addition gets written up with its price and schedule impact, approved BEFORE the work happens. AI drafts it in minutes from the original estimate — no awkwardness, just paper.",
     q:"The “one little bathroom” gets…",
     ch:[{t:"Just do it — keep the client happy",out:{r:"bad",concept:"Change orders",why:"Free bathrooms today, bankruptcy mañana. Unpaid scope is the quiet killer of good crews.",beat:"The crew builds it beautifully. Nobody pays for it."}},
         {t:"A written change order — price and timeline impact, AI-drafted, client-approved before work starts",out:{r:"ok",concept:"Change orders",why:"The AI turns the estimate into a change order in minutes; the client signs knowing exactly what it costs. Everyone stays friends AND solvent.",beat:"The client signs. Don Güero frames the change order like a diploma."}},
         {t:"Refuse all changes — the contract is the contract",out:{r:"mid",concept:"Change orders",why:"Protects the margin, loses the relationship — and remodels ALWAYS change. Half credit for spine, zero for flexibility.",beat:"The client calls someone else for the next job. And the next."}},
         {t:"Do it, and quietly add it to the final invoice",out:{r:"bad",concept:"Change orders",why:"Surprise charges are how trust — and occasionally court dates — get lost and found. Paper first, work second.",beat:"The final invoice starts a shouting match in two languages."}}]}}},
 {npc:"lupe",title:"Permit purgatory",start:"a",nodes:{
  a:{say:"Three projects are sitting dead because the permits aren't filed. Same forms, same city, every time — owner info, scope, drawings list, fees. I spend my Sundays copying the same data into the same boxes. There has to be dignity somewhere in this.",
     codex:"Repetitive paperwork is document automation's home turf: the project data already exists, so AI can fill the standard forms from it and track each permit's status. The human reviews before filing — a wrong permit is worse than a slow one.",
     q:"How do the permits get done?",
     ch:[{t:"Find a guy who knows a guy at the city",out:{r:"bad",concept:"Document automation",why:"The guy retires, the shortcut becomes a scandal, and the projects stay dead. Not a system.",beat:"The guy's cousin quotes a “consulting fee.” Lupe hangs up."}},
         {t:"AI fills the forms from the project data, Lupe reviews before filing, a tracker follows each permit's status",out:{r:"ok",concept:"Document automation",why:"The data exists once, the forms fill themselves, the human signs off, and nothing gets lost in purgatory again. Sundays return to Lupe.",beat:"Three permits filed by lunch. Lupe takes an actual weekend. The city is confused."}},
         {t:"Keep doing them by hand — it's tradition",out:{r:"mid",concept:"Document automation",why:"It works, slowly, and eats the estimator who should be estimating. Half credit for reliability, at the cost of Sundays.",beat:"Lupe's coffee goes cold over form B-247. Again."}},
         {t:"Outsource all permits to a consulting firm",out:{r:"mid",concept:"Document automation",why:"It works — at a fee, forever, and the capability never comes in-house. Half credit: delegated, not solved.",beat:"The consultant uses the same AI tool. Lupe watches, invoiced."}}]}}},
 {npc:"priya",title:"Say it so it's true",start:"a",nodes:{
  a:{say:"The support bot's answers SOUND great — confident, polished, wrong maybe one time in ten. Nobody can tell which time. Marketing loves the tone. I hate the tone. Fix the wording.",
     codex:"Trust is built with calibrated language: instructions that make the bot cite its source, mark uncertain answers as uncertain, and say 'I don't know' when nothing supports an answer. 'Be accurate' is a vibe — cite, qualify, and refuse are behaviors.",
     q:"What goes in the bot's instructions?",
     ch:[{t:"Write “be accurate and helpful” at the top",out:{r:"mid",concept:"Calibrated language",why:"A vibe, not a behavior. Models follow concrete verbs; “be accurate” measures nothing. Half credit — harmless, useless.",beat:"The bot stays confidently wrong, but now politely."}},
         {t:"Cite the source for every claim, mark uncertain answers as uncertain, and say “I don't know” when nothing supports it",next:"b"},
         {t:"Make it sound MORE confident — customers like certainty",out:{r:"bad",concept:"Calibrated language",why:"Confident wording on wrong answers is how trust dies at scale. That's polishing the failure.",beat:"Marketing applauds. Camila opens a new spreadsheet."}},
         {t:"Append a legal disclaimer to every answer",out:{r:"mid",concept:"Calibrated language",why:"Cover isn't candor — by the third message, users are trained to skip it. Half credit for lawyer instincts.",beat:"Users scroll past the disclaimer at record speed. All of them."}}]},
  b:{say:"Better. Now the live one: a caller asks “how many locations take the app?” — retrieval finds nothing current. The bot has to say SOMETHING. Word it.",
     codex:"When you can't verify, the trustworthy shape is: state what you CAN confirm, name what you can't, and hand over the path to the answer. Precision about your own limits is what accuracy sounds like.",
     q:"The bot's best reply is…",
     ch:[{t:"“Around 300 locations!” — probably close",out:{r:"bad",concept:"Verifiable claims",why:"A confident guess is a lie with good posture. One wrong number unravels every right one that came before it.",beat:"It was 41. A journalist was on the line."}},
         {t:"“I can't verify the current count. As of the last update it was 38 — here's where the live list is.”",out:{r:"ok",concept:"Verifiable claims",why:"Confirms the known, names the unknown, hands over the path. That wording IS the trust product.",beat:"Priya reads it twice. “Ship the wording.” The highest praise she knows."}},
         {t:"“I cannot answer that question.”",out:{r:"mid",concept:"Verifiable claims",why:"Honest but lazy — refusing everything unverifiable throws away the partial truth you DO have. Half credit.",beat:"The caller asks a human, who reads them the same last update."}},
         {t:"Answer normally, tuck “estimates may vary” at the end",out:{r:"mid",concept:"Verifiable claims",why:"Uncertainty in the footnote is certainty in the headline. Placement is part of wording. Half credit.",beat:"Nobody reads footnote three. Ever."}}]}}},
 {npc:"xochi",title:"The collar drop",start:"a",nodes:{
  a:{say:"Ah, the AI person! Look — La Obra builds the barrio, I dress it. I want a collar line for the neighborhood's pets: Frederick, Canela, the whole cast. I can sketch, but these AI image tools… how do we DESIGN with them without losing the craft?",
     codex:"Image models are variation engines, not designers. The working pattern: the designer sets the brief, AI generates dozens of directions, the human curates and refines the winners — and a pick only becomes real once it's a structured spec (a tech pack): materials, measurements, colorways. Taste stays human; the machine does volume.",
     q:"How does the collar line get designed?",
     ch:[{t:"One prompt, first image, straight to production",out:{r:"bad",concept:"AI-assisted design",why:"No curation, no spec, no sizes — a first output is a mood, not a product. Production needs measurements, not vibes.",beat:"The sample arrives sized for a horse. Frederick declines to comment."}},
         {t:"AI generates variations against Xochi's brief; she curates, and the pick becomes a tech pack — materials, sizes, colorways",next:"b"},
         {t:"Copy that famous designer's collar and have AI restyle it a little",out:{r:"bad",concept:"IP & originality",why:"A restyled copy is still a copy — legally radioactive and creatively hollow. AI makes imitation faster, not legal, and the barrio deserves its own look.",beat:"Dana appears in the Studio doorway holding a cease-and-desist. Just so you know what one looks like."}},
         {t:"Hand-sketch everything like always, no AI",out:{r:"mid",concept:"AI-assisted design",why:"The craft is real and the taste is the point — but one designer exploring five directions by hand loses to the same designer curating fifty. Half credit for standards.",beat:"Week two: three beautiful sketches, ninety unexplored ideas."}}]},
  b:{say:"The tech pack came out gorgeous. Now the launch — these are virtual fits for the town's pets. How do we ship the line?",
     codex:"Curation is quality control for creative goods. Small drops with a human QA pass — does every piece fit every body it's sold for? — keep a catalog worth browsing. Auto-generating infinite listings floods the shelf with slop, and “free everything forever” just means the work can't continue.",
     q:"The drop strategy is…",
     ch:[{t:"Small curated drops; every piece checked on every pet body before listing",out:{r:"ok",concept:"Curation as QA",why:"Each drop is small enough to check and special enough to want. The eval mindset, applied to fashion: test on every body shape before it ships.",beat:"Drop one sells out by sunset. Frederick models the gold collar with unbearable dignity."}},
         {t:"Auto-generate and auto-list new items daily",out:{r:"bad",concept:"Curation as QA",why:"An infinite uncurated catalog is a landfill with a search bar. Nobody browses slop twice.",beat:"Item #4,072 is a collar with three buckles and no hole. A confused pigeon already bought it."}},
         {t:"Everything free, forever, for everyone",out:{r:"mid",concept:"Curation as QA",why:"Generous — and unsustainable. Free is a launch tactic, not a plan; the line dies when the work can't pay for itself. Half credit for heart.",beat:"Month two: Xochi quietly takes a mural commission to fund collar three."}}]}}}
];
