/* Meridian Quest content pack — UI strings, every player-facing line, EN+ES in lockstep. */
const UI={
 en:{
  in1:"Meridian Labs needs an AI delivery hero. The old lead fine-tuned something he shouldn't have and was never seen again.",
  in2:"The office is a world. Roam it — hallways, the kitchen, the corner offices. Coworkers with a ❗ have quests; walk up and talk, in any order. Some decisions open follow-up decisions.",
  in3:"Every call goes in your file — first try, second, or third. A wrong one earns you a verdict and another look; the quest stays open until you make the right call, and nothing you've built here is ever taken away. That file becomes a real report you can walk out with. Ladder: Junior → Delivery Lead → Senior Lead → AI Legend.",
  in4:"Choose your class:",
  classes:{architect:["The Architect","You see systems. Meridian's diagrams fear you."],diplomat:["The Diplomat","Bilingual, unflappable. CFOs sign things near you."],operator:["The Operator","You ship. Production logs whisper your name."]},
  crTitle:"Create your hero",lbName:"Name",lbOutfit:"Outfit",lbShirt:"Shirt / jacket",lbSkin:"Skin tone",lbHairC:"Hair color",lbHairS:"Hair style",begin:"Badge in",
  outfits:[["casual","Casual"],["formal","Formal 👔"]],styles:[["cap","Short"],["long","Long"],["curly","Curly"],["buzz","Buzz"],["spiky","Spiky"],["pony","Ponytail"],["afro","Afro"],["mohawk","Mohawk"],["braids","Braids"],["flat","Flat top"],["buns","Buns"],["edgar","Edgar"],["fade","Taper fade"],["mullet","Mullet"],["broccoli","Broccoli"],["bald","Bald"]],
  worldTag:"Meridian HQ · find the ❗",
  hintSwipe:"Touch anywhere on the screen and drag to walk · release to stop · ⚙️ to switch controls.",
  hintJoy:"Joystick or arrow keys to roam · walk up to a ❗ coworker and Talk · ⚙️ to switch controls.",
  hintPad:"D-pad or arrow keys to roam · walk up to a ❗ coworker and Talk · ⚙️ to switch controls.",
  drwCtl:"🎮 Controls",drwLook:"🎨 Picture",drwSound:"🔊 Sound",drwGame:"⚙️ Game",
  setTitle:"Settings",lbCtl:"Movement controls",swipeB:"👆 Swipe",joyB:"🕹️ Joystick",padB:"✛ D-pad",lbLang:"Language",lbAdm:"Admin mode — touch tiles to reshape the office",admOff:"Off",admOn:"🛠️ On",openLab:"📝 Text lab",closeSet:"Done",
  brushes:["Floor","Wall","Desk","Plant","Rug","Door","Table","Fridge","Stove","Character"],
  nmTitle:"New character",nmLb:"Name them — some names carry magic",nmOk:"✨ Create",nmCancel:"Cancel",
  npcMade:n=>n+" moved into the barrio.",npcGone:"They moved away.",npcFull:"The barrio is full (12 friends max).",
  nmEditTitle:"Edit character",nmSave:"💾 Save",nmLook:"🎲 New look",nmOut:"📦 Move out",npcSaved:"Updated.",npcLook:"New look!",npcLease:"They have a lease — the original townsfolk stay.",
  chill:["Nice day for standing exactly here.","I'm not in the way. I AM the way.","The trolley was late once. Once.",
   "I heard the office dog keeps a better calendar than me.","Just vibing. It's a whole job if you do it right.",
   "The jacarandas only bloom like this when the week's going well."],
  growthUp:"🏗️ Progress! The site across the street is taking shape.",
  pigeon:["Coo.","The pigeon judges your crosswalk technique.","She was here before the city. She'll be here after."],
  loro:["¡Ándale, jefe!","Lorenzo supervises. Lorenzo approves.","¡Qué bonito trabajo!"],
  gato:["Mrrrp. The street cat allows it.","One ear flicks. You have been acknowledged.","Somebody feeds this cat tamale scraps. The cat runs the place."],
  mariposa:["It rests on a bloom, just for you.","Wings like papel picado.","It does one slow loop around your head. Blessed."],
  colibri:["It hovers an arm away, inspecting you. You pass.","A tiny emerald helicopter with opinions.","Doña Rosa says a colibrí visit means good news is coming."],
  tlTitle:"Text lab",tlHint:"Edit names, quest titles and bump lines (JSON). Applies to the current language.",tlApply:"Save",tlClose:"Close",tlOk:"Texts updated.",tlErr:"That JSON didn't parse — nothing changed.",
  levels:["Junior","Delivery Lead","Senior Lead","AI LEGEND"],
  quest:"Quest",followup:" · follow-up",codexLb:"📜 Codex",
  okH:"⚔️ QUEST COMPLETE",midH:"🟡 SHIPPED WITH INCIDENTS",badH:"💔 SLIP — reputation takes a hit",
  lvlUp:"⬆ LEVEL UP — you are now ",
  nextBack:"Back to the office",nextEnd:"Claim your title",nextDoom:"Face the consequences",
  talkPre:"💬 ",
  tut1:"This is you. Roam with the joystick or arrow keys.",tut2:"Desks, plants and walls just block you — coworkers with a ❗ have quests. Walk up and Talk.",
  admToast:"Admin on. Pick a brush, tap tiles. With great power comes the ability to wall yourself in.",
  undoLb:"Undo",undoToast:"Edit undone.",undoEmpty:"Nothing to undo.",
  tlFindPh:"Search text…",tlNoHit:"No match.",
  dog:["Woof!","Frederick approves.","Frederick is herding you back to work."],
  treatLb:"🦴 Treat Frederick",fredHeart:"Frederick: ❤",
  petCat:"🐾 Pet Canela",petPig:"🐾 Greet Paloma",petLoro:"🦜 Say hi to Lorenzo",petGato:"🐾 Pet the street cat",petFly:"🦋 Watch the butterfly",petColi:"🌺 Watch the colibrí",
  fredUnlock:"Frederick trusts you now… and he has paperwork. 🐾 Secret side quest unlocked — treat him again to open it.",
  carePackToast:"📦 New in ⚙️ → Export: Frederick's care pack — his sheet + reminders, ready for your own pet.",
  fredDoneToast:"🎀 Mod unlocked: Frederick's red bandana.",
  locs:{ta:"Taller Herrera",pa:"Panadería La Espiga",li:"Limpieza Velázquez",no:"Nolasco Tax & Notario",hq:"Meridian HQ",f2:"Floor 2 · Your office",st:"Meridian Street",lc:"La Cocina",lo:"La Obra · Studio",ex:"Calle Dos · Expansion block",me:"El Mercado Robles",pk:"El Parque 🌈"},
  chat:{beto:["We pour, we cure, we move down the block. Don Güero says hi.","Ask me again in two weeks, primo. Whatever's behind that fence will be a building."],
        kike:["Straight walls, straight prompts — same discipline.","The AI did the material takeoff. I checked every line. We're friends now."],
        mari:["From the crane you can see Güero's whole plan.","The lift schedule is AI-sorted — weight, wind, order. Smooth all day."],
        chava:["Chile is the fastest button, güey. Whoever put carne four screens in never stood in this line.","Doña Chelo says I broke the numbers. I say the numbers broke me first.","Frijol gets the trimmings. Frijol has never worked a day."]},
  arrive:{ta:"Taller Herrera. Brake dust and coffee.",pa:"La Espiga. The ovens have been on since four.",li:"Limpieza Velázquez. The floor is wet. It is always wet.",no:"Nolasco Tax & Notario, upstairs. Take a number.",hq:"Meridian HQ.",f2:"Floor 2. North light, the wall where your work goes, and the old lead's machine still logged in on the desk.",st:"Street level. Mind the crosswalk.",lc:"La Cocina — smells like consommé and opportunity.",lo:"La Obra's studio — you helped build this. Every drawing here becomes a building.",ex:"Calle Dos — the town grows east. The crew stages here; whatever they're building is somewhere else.",me:"El Mercado Robles — cilantro, cumbia on a radio, and a business with opinions.",pk:"El Parque — grass, river, rainbow bridge. No clock in here."},
  trolley:{title:"🚋 Barrio Trolley",note:"The MQT line — every district, one hop. Where to, consultant?",here:"you are here",soon:"Barrio Norte — coming soon",close:"Stay here"},
  cat:["Mrrp.","Canela blinks slowly. You are accepted.","The health inspector doesn't know about Canela. Keep it that way."],
  endGo:"▶ Out to the street",
  waitingAt:p=>"Somebody in "+p+" has something to say.",
  weekTwoToast:"Eight in the morning. Doña Chelo is unlocking the gate on the southwest lot — and leaving it open. Nothing behind you closes either.",
  mepi1:"Saturday, closing time. Doña Chelo counts the drawer twice, the way she has for thirty years, and this time the number matches what the screen said all week. “You didn't build me a robot,” she says. “You built me a Tuesday I can trust.” Frijol sleeps on the scale. Outside, somebody is laying track. Before you're out the door she's on the landline. “Tacho. He told me to stop paying him for something. Send him your worst.”",
  mepi2:"Saturday, closing time. Some of it stuck, some of it Nando quietly went back to doing by hand. Doña Chelo shrugs. “Half of it works. That's more than the last guy.” She writes your name on the wall by the register, next to the permit — and under a name in older handwriting you don't recognize yet. On the landline, later: “Tacho. Half of what he did works. That's more than the last one.”",
  mepi3:"Saturday, closing time. The mercado survived you. Most of the list is still a list, and the pilot is a folder nobody opens — but Doña Chelo hands you a bag of pan dulce anyway. “Come back when you've thought about it.” The door does not lock behind you. A week later she phones Tacho and says one thing: “He's honest about what he doesn't know. Start there.”",
  expBtn:"📤 Export (beta)",expTitle:"Export (beta)",
  expHint:"Skeleton v1 — your play data as JSON, ready to copy. Future: typed documents from real work (decision report), email delivery, conversation export.",
  expCopy:"Copy",expCopied:"Copied to clipboard.",
  exTabJson:"Play data",exTabCare:"🐾 Care pack",exIcs:"📅 Reminders (.ics)",
  exTabRep:"📄 Decision report",exDl:"⬇️ Download (.md)",
  repHint:"Every call you made, written up as a portfolio piece — the question, your answer, the concept it tested, and why it landed. Copy it, or download the Markdown and hand it to a hiring manager.",
  repHead:(n,lv,x,mx,he,dt)=>`# Decision Report — ${n}

*Meridian Quest · judgment calls under pressure · ${dt}*

**Level:** ${lv}  ·  **XP:** ${x}/${mx}  ·  **Grade:** ${he}`,
  repSum:(d,q,pct)=>`**${d} decisions across ${q} quests — ${pct}% solved on the first attempt.**`,
  repEmpty:"No decisions recorded yet. Answer a quest and this report writes itself.",
  repRole:(c,q,pct)=>`${c} ${c===1?"decision":"decisions"} across ${q} ${q===1?"quest":"quests"} · ${pct}% first try`,
  repL:{roles:"Roles practiced",side:"Personal side quest",
    question:"Question",call:"Your call",verdict:"Verdict",why:"Why",
    ok:"✅ Solid call",mid:"◐ Partial credit",bad:"✕ Miss",
    advanced:"Correct — advanced to the follow-up.",
    concepts:"Concepts practiced",attempts:"attempts",attempt:"attempt",
    foot:"Generated by Meridian Quest — a practice gym, not a certificate."},
  careHint:"Frederick's ops system as a real deliverable — copy the sheet, download the recurring reminders, swap in your own pet's details.",
  carePack:(n,tr,p)=>`# 🐾 ${p.n.toUpperCase()}'S CARE PACK
Kept by ${n} · Meridian Labs
One source of truth for one very good pet.

## Daily
- ${p.am}  Breakfast
- Morning walk — 20 min
- ${p.pm}  Dinner
- Evening walk — 20 min
- Treats: 3/day max (in-game treats given to Frederick: ${tr})

## Recurring — if it repeats, it gets a reminder
- Flea/tick + heartworm ....... monthly, the 1st
- Grooming .................... every 8 weeks
- Weigh-in .................... every 3 months
- Vet checkup + vaccines ...... yearly (book 2 weeks ahead)
- Content batch day ........... monthly: AI drafts the captions, a human approves

## House rules (as decided in the quest)
1. This sheet is the single source of truth — not the fridge, not three people's heads.
2. Memory is not a system — every cycle above lives in a shared calendar (see the .ics).
3. One shared checklist; whoever does the feeding checks it off.
4. Nothing posts as ${p.n} without human approval. ${p.n} cannot approve. ${p.n} is a very good pet.`,
  careEvents:pn=>["🐾 Flea/tick + heartworm — "+pn,"🐾 Grooming — "+pn,"🐾 Weigh-in — "+pn,"🐾 Vet checkup + vaccines — "+pn,"📸 "+pn+" content batch day"],
  petPh:"Pet's name",
  wdTitle:"🧵 Xochi's Collar Drop",wdNote:"Fresh from the tech pack — dress the neighborhood. Frederick roams HQ; Canela holds court at La Cocina. Changes save instantly.",
  wdBandana:"Bandana",wdCollar:"Collar",wdCape:"Cape",
  wdUnlockToast:"🧵 Wardrobe unlocked — in ⚙️ Settings, or with Xochi once her quest is beaten.",
  wdBtn:"🧵 Wardrobe",
  tpBtn:"🎫 Trolley Pass",tpTitle:"🎫 Trolley Pass",
  tpNote:"Your save, stamped as a transit pass. Scan the code with your other device's camera, or share the pass to it — boarding over there always asks first.",
  tpShare:"📤 Share pass",tpCopy:"🔗 Copy link",tpCopied:"Pass link copied.",
  tpFoundLb:"🎫 Trolley Pass found",
  tpFoundTx:(n,x,d,q)=>`${n} rode in on the trolley — ${x} XP, ${d}/${q} quests.`,
  tpReplace:n=>`Boarding replaces this device's save (${n}).`,
  tpBoard:"🎫 Board with this save",tpSkip:"Keep this device's save",
  mpBtn:"🌐 Multiplayer 🚧",mpTitle:"🌐 Multiplayer",
  mpNote:"🚧 Under construction. The MQT crew is laying track to Barrio Norte — one day other consultants will roam these streets with you. For now, the office is all yours. (Hard hats stay on until the line opens.)",
  lbTheme:"Color theme",
  updToast:"updated! New stuff is in.",lbSeason:"Season",seasonAuto:"📅 By the calendar",seasonOff:"Year-round",lbCam:"Camera",camTop:"🗺️ Top-down",camFront:"🏘 Front 2.5D",camIso:"◆ Isometric",cam3d:"⛰ 3D",
  ballLb:"🎾 Throw the ball",ballNoRoom:"No room to throw here.",
  fetchYes:["Delivered! Slightly slobbery, entirely perfect.","He brings it back like it's his whole career.","Retrieved. The tail says do it again."],
  fetchNo:["He looks at the ball. He looks at you. He sits.","The ball rolls. He has decided it is the ball's problem.","Not today. He is a dog of principle."],
  howl:"AWOOOOO…",
  beagleTreat:["A treat! The tail achieves liftoff.","He accepts it gently, like a gentleman.","Crunch. You are his favorite person for the next hour.","Fueled up — he'd fetch anything for you right now."],
  cmdLb:"🎓 Commands",
  cmdSit:"Sit",cmdDown:"Down",cmdStay:"Stay",cmdCome:"Come!",cmdFollow:"Follow me",
  cmdOkSit:"He sits. A professional.",cmdOkDown:"Down. Fully deflated.",
  cmdOkStay:"He stays. His eyes never leave you.",cmdOkCome:"He comes running, ears flying.",
  cmdNo:["He looks at you with enormous love and does nothing.","He heard you. He is considering it.","A leaf was more interesting. Try again."],
  cmdTrained:n=>`Training +1 — ${n} is getting better at this.`,
  followOn:"He trots to your side.",followOff:"Free dog. He'll stay close anyway.",
  sniff:"The ancient greeting, performed correctly.",
  chaseToast:"Zoomies! The park approves.",
  dupDog:n=>`There's already a dog named ${n} here.`,
  adoptBreed:"Breed",adoptColor:"Coat",
  breeds:{beagle:"🐶 Beagle",lab:"🦮 Lab",chi:"🐕 Chihuahua"},
  renameLb:"✏️ Rename",renameAsk:"A new name for this good dog:",renGo:"💾 Rename",
  renameDone:n=>`They answer to ${n} now. Instantly, because dog.`,
  rehomeLb:"🏡 Rehome",
  rehomeDone:(n,f)=>`${n} moved in with ${f}. Nobody is ever deleted in this city — visit anytime.`,
  loveLb:"💗 I love you",
  loveLines:["His whole body wags. He knows. He's always known.","He presses his head into your hand. Message received.","Tail thump. Slow blink. I love you too, says the dog."],
  leashLb:"🦮 To the park!",leashToast:n=>`${n} takes the leash in his mouth. He knows the way — over the rainbow bridge.`,
  parkArrive:"🌈 El Parque! Throw the ball, share a treat, listen for howls — there is no clock here.",
  bandLb:"🎀 Bandana",bandToast:"🎀 New look!",bandOff:"🎀 Au naturel.",
  adoptLb:"🏠 Adopt a dog",adoptAsk:"Name your new best friend:",adoptGo:"🐶 Welcome home",adoptX:"Not yet",
  adoptDone:n=>`🐶 ${n} is home. The park just got better.`,
  parkFull:"The park is full — four dogs is already a lot of dogs.",
  parkTitle:"🌈 A day at El Parque",
  parkSum:(f,t,h,d)=>`🎾 ${f} ${f===1?"fetch":"fetches"} · 🦴 ${t} ${t===1?"treat":"treats"} · 🐶 ${h} ${h===1?"howl":"howls"} · 🕳 ${d} ${d===1?"hole":"holes"}`,
  parkLove:"He loves you. That was the whole game.",
  parkTeaser:"One day Sonny gets a whole game of his own. This park is the preview.",
  parkClose:"↩ Back to the city",isoEdit:"Switch the camera to Top-down to edit tiles.",lbMusic:"Music",musOn:"🔊 On",musOff:"🔇 Muted",tunes:["🎼 Auto","Lo-fi","Bells","Marimba","Dusk"],
  themes:{meridian:"🏢 Meridian",forest:"🌿 Forest",fairy:"🧚 Fairy",sunset:"🌇 Sunset",custom:"✨ Custom"},
  teOpen:"🎨 Theme editor",teTitle:"🎨 Theme editor",
  teFrom:"Start from a preset (clones it into ✨ Custom)",teModeLb:"Editing variant",
  teFix:"🪄 Auto-fix contrast",
  teSaved:"✨ Palette saved — pick it any time under Color theme.",tePalsLb:"Saved palettes",teNamePh:"Palette name",palFull:"The wardrobe is full (8 palettes) — evict one first.",palNames:{meridian:"Meridian",forest:"Forest",fairy:"Fairy",sunset:"Sunset"},teFixed:"🪄 Text colors nudged until every pair passes the contrast audit.",
  retryNote:"❗ This one stays open — come back and make the better call.",
  retryNoteFred:"🦴 Frederick will reopen the folder for another treat.",
  mapTitle:"Village map",vmF2:"Floor 2",vmHQ:"Meridian HQ",vmSt:"Meridian Street",vmLc:"La Cocina 🌶️",
  vmSite0:"🚧 Construction site",vmSite2:"La Obra · Studio 📐",vmPlots:"Reserved lots — El Mercado & more",vmHere:"◉ you are here",
  goTitle:"🕯️ The floor stopped trusting you",
  goEpi:"Priya finds you in the parking lot. “Three bad calls and the floor stopped trusting you. That's the week — it isn't the job.” She taps the folder under her arm. “Nothing in here got closed. Same desk Monday, and this time you've read the Codex.”",
  mgoEpi:"Saturday. Doña Chelo hands you a bag of pan dulce and does not ask for the keys. “You learned on my floor. That's what a floor is for.” What you finished, the mercado keeps. What you didn't is still on the counter in a folder with your handwriting on it, and the gate opens at seven, same as always.",
  endStay:"↩ Back to the city",
  endStayToast:"The city is yours to walk. Whatever's still open stays open.",
  /* Las cuatro puertas — the four districts' Saturdays, their next-lot toasts, their burnouts (Nacho, 2026-09-02) */
  tallerToast:"Eight in the morning. The roll-up door on the southeast lot is halfway up and a Caprice is on the sidewalk. Don Tacho is on the phone with Doña Chelo, and he doesn't look happy about it. Nothing behind you closes.",
  tepi1:"Saturday, six o'clock. The book is on the shelf next to Tacho's manuals, spine out, closed. Yesenia leaves at six for the first time in four years and Tacho says so out loud, which from him is a parade. Moy is at the counter teaching the intake flow to the kid from the tire place. Tacho hands you a key to the side door — “for when the trolley opens and you need somewhere to sit” — and picks up the shop phone before you're off the lot. “Licha. The computer guy. He didn't sell me anything. Ask him what you throw away.” Tuerca is asleep on the hood of the Caprice. “That's Tuerca. She lives here now. I didn't decide it.”",
  tepi2:"Saturday, six o'clock. Half of it stuck. Yesenia still keeps the book — only for the jobs she doesn't trust the system with yet, and the pile is thinner every week. Tacho wipes his hands and gives you the truest line in the building: “You didn't sell me anything. That's why I let you stay.” He phones Licha on Monday and says less than that. Tuerca has moved onto the Caprice anyway; nobody asked her either.",
  tepi3:"Saturday, six o'clock. The intake assistant is switched off and the book is exactly as thick as it was. Nothing broke, nothing burned, and Tacho is kind, which is worse and better than angry: “You came, you looked, and you were honest about what you didn't know. Most of them lie in the first ten minutes.” Moy walks you to the gate and asks, quietly, if he should stop using the phone thing. You tell him no. You tell him what to check. A week later Tacho phones Licha and says one sentence about you; it's a fair one. Tuerca moves in anyway.",
  tgoEpi:"Saturday. Tacho doesn't take the side-door key back, because he never gave it. “You learned on my floor. Floors are for that.” The book is on the counter with a page in your handwriting, and the roll-up door goes up at seven.",
  espigaToast:"Five in the morning on Calle Dos. The lights are on at the west lot and the ovens are already hot — Doña Licha got a phone call. Nothing behind you closes.",
  eepi1:"Saturday, closing. Two conchas on the last tray, nothing in the merma bin, nobody turned away since Tuesday. Doña Licha pins the page above the oven next to the pars in her own handwriting and hands you a rosca in September. “For the road, vecino. I know what month it is.” Tito is asleep — actually asleep, at a reasonable hour, somewhere else. Vero's crew comes in to mop and Licha says it over the counter, no phone needed: “Vero. This one counts. Give him your worst crew.” Bolillo is asleep in the flour bin. Nobody has ever gotten him out of it.",
  eepi2:"Saturday, closing. The sheet runs; Tito trusts it on weekdays and his gut on Fridays, and the trash is lighter than it was. Licha hasn't pinned anything above the oven — the pars are still in her head — but Sol's strip has a time column now, and on Thursdays it's in Licha's handwriting. She says it to Vero over the counter, shorter: “He counts. Try him.” Bolillo sits in the flour bin with an expression.",
  eepi3:"Saturday, closing. The sheet is in a drawer and Tito is back to deciding at 3:45 alone. But Sol's strip has a column it didn't have, and nobody told her to stop. Licha gives you a bag of pan de ayer — “It's still good. So are you, probably.” — and says nothing to Vero for a week. Then she does, one sentence, over the counter, and it's fair. Bolillo follows you to the door and stops there. It's his door.",
  egoEpi:"Saturday. Licha hands you pan de ayer and doesn't ask for the sheet back. “You learned in my kitchen. That's what an oven is for.” The strip is on the board with a column in your handwriting, and the ovens go on at four.",
  velazquezToast:"Ten at night on Calle Dos. A van with a mop bucket is parked on the east lot and somebody is unlocking a door by phone light. Doña Vero got a referral over a bakery counter. Nothing behind you closes.",
  vepi1:"Saturday. The bid went in Friday with the word “kitchen” on all twelve pages, in pen. The page is above the dash where the sticky notes were — three numbers, the rollout order, and a line signed by Vero: this app counts work; it never tracks where you are. Chente read it twice and called you compañero once, by accident, and didn't take it back. Vero puts an envelope in your hand — the pilot review — and says, “Take this to Nolasco. He reads.” Pelusa is asleep on the route sheet. The route sheet is a printout now. Pelusa has not noticed.",
  vepi2:"Saturday. Three crews on the app, six on Karla's phone, and the 5:40 calls are down to Tuesdays. Marta's paper is on the map as the exception it is. Vero looks at the bid and says the honest thing: “Twenty people is next year. Nine people is now, and nine is better than it was.” She sends you to Nolasco with the envelope, and a shorter note inside it. Pelusa rides along. Pelusa always rides along.",
  vepi3:"Saturday. The tablet is back in the glovebox and Karla's dashboard has sticky notes on it again. But one of them says “Marta no martes,” and it's the first time anybody wrote it down. Vero doesn't send you to Nolasco with an envelope. She sends you with a sentence, a week later, and it's fair: “He listened to Chente. Nobody listens to Chente.” Pelusa watches you go from the dash. She isn't judging. She's a cat; she doesn't have to.",
  vgoEpi:"Saturday. Vero doesn't take the tablet back; it was never yours. “You learned in my van. That's what a van is for.” The page is on the dash with a line in your handwriting, and the crews go out at ten.",
  nolascoToast:"A walkup off Calle Principal, second door. A sign in two languages, a light on upstairs, and a cat sitting exactly where a doorbell would be. Lic. Nolasco has a file with your name on it. He writes everything down. Nothing behind you closes.",
  nepi1:"Saturday. Nolasco stamps the last page of your report and says what the stamp means once more, because he says it to everyone: “It's an acknowledgment. You signed it in front of me. It doesn't mean it's true.” He looks at the four letters beside it. “It is, though.” He hands you a key to a file cabinet — “It goes upstairs. The record needs a body.” — and, because he files everything, a note for the dog: “Somebody should tell Frederick there's going to be a ceremony. He'll want to host.” Timbre sits in the doorway where a doorbell would be. You step over her. She allows it.",
  nepi2:"Saturday. Nolasco reads every page before he stamps anything, which takes a while. Two of your entries have the word extension written in the margin, in his hand. “You filed an extension on these. Good. Most people file a guess.” The cabinet still goes upstairs; one drawer is yours to fill. Timbre is on the stairs. She was on the stairs before the stairs.",
  nepi3:"Saturday. Nolasco reads all of it and says the longest thing anyone in the barrio has said to you, and none of it is unkind: the sign, the nephew, the stranger — what each one would have cost a family, and what you did the second time. “I don't grade people, colega. I file them. This one goes in the drawer marked open.” The cabinet goes upstairs anyway, with one empty drawer and your name on it. Timbre walks you down the stairs. She doesn't do that for everyone; she doesn't do it for anyone.",
  ngoEpi:"Saturday. Nolasco doesn't take the file back; it was never his to keep. “You learned in my office. That's what an office is for.” The page is on Bere's desk with a line in your handwriting, and intake opens at nine.",
  lastToast:"Nothing else opens tonight. On the way down the stairs you can hear it from the north end: the last segment going onto the ground, and somebody arguing about folding chairs.",
  replayArm:"⚠️ Tap again to erase everything",
  endScore:(x,m,h)=>`${x}/${m} XP · ${h}/3 hearts intact`,
  endGrade:(x,m,g)=>`${x}/${m} XP · ${g}`,
  grades:["scraped through","solid work","clean — first try, nearly every time"],
  lbStakes:"Stakes (admin)",stkNone:"None",stkHearts:"❤ Hearts",
  stkToast:m=>m==="hearts"?"Hearts on. Wrong calls cost one — nothing else.":"Hearts off. Nothing to lose but the grade.",goScore:(x,d,n)=>`${x} XP · ${d}/${n} quests completed`,
  epi1:"Friday, 6pm. The VP stands up when you enter. “Flawless week — and you walked your own path. The agents program is yours.” You take the long way out, past the wall where Nacho is chalking the outline of a block that isn't built yet.",
  epi2:"Friday, 6pm. “Strong week,” says the VP. “Some incidents shipped, but you owned the floor.” Priya nods on your way out. Week Two is coming.",
  epi3:"Friday, 6pm. You survived — barely. The VP slides the Codex back across the table: “Study. Everything you didn't answer is still sitting there waiting for you. That's not a punishment, that's a Tuesday.”",
  replay:"New game +",replayToast:n=>`Back at it, ${n}. Same office, wiser hero.`,
  contBtn:(n,x,d)=>`▶ Continue as ${n} — ${x} XP, ${d}/${QEN.length} quests`,
  langQuick:"🌐 Español",
  flavor:{"▭":["Blank paper, pinned up ready. Nothing has earned this spot yet."],
    "▤":["A stapled sheaf, pinned flat. Yours — walk up and read it."],
    "□":["Your boxes. Taped, labelled in your own handwriting, still where the movers left them."],
    "|":["Three panes of north light. The back lot, the old road out, and the graded line where the trolley is going."],
    "=":["Painted block. Tacho painted it himself, badly, on purpose."],"6":["Tacho's Caprice. Do not lean on it. He will know."],"0":["A tire stack. Somebody's spare, somebody's problem."],"7":["The lift. A car in the air is a car that has been listened to."],"8":["The tool chest. Every drawer has a place and every place has a drawer."],"&":["La Espiga. Conchas in the window since six."],"!":["Limpieza Velázquez. Cleaner than your kitchen."],"▣":["The deck oven. Two hundred and thirty degrees of patience."],"▯":["A file cabinet. Somebody's whole year in a drawer."],"⊔":["A guest chair. For whoever needs to sit and talk."],"○":["The dog bed. Not for you."],D:["Just a desk. The monitor is judging you anyway.","A coworker's desk. Their kombucha, their rules."],K:["The coffee counter. Sacred ground.","The coffee machine. It has seen things."],P:["A potted plant. It's doing its best.","The office ficus. Load-bearing morale."],"#":["A wall. Solid argument.","That's a wall. Even AI Legends respect walls."],"+":["A door. It opens by walking through it. Technology.","Doorway detected. You may proceed."],B:["The building facade. Sturdy. Corporate.","Brick. It was here before you and will be here after."],F:["Construction fence. Hard hats beyond this point."],G:["Steel girders. The future has scaffolding."],C:["A traffic cone. Respect it."],X:["🚧 An empty lot with a fence around it and a permit taped to the post. Every business on this street started exactly like this."],T:["A dining table. The tablecloth is non-negotiable.","Reserved. Probably for Canela."],W:["The walk-in fridge. Chuy's forecast is taped to it. It is law.","Cold storage. Where margins live or die."],V:["The stove. Six burners of consommé diplomacy.","Hot. Chuy's domain. Ask before touching."],A:["A drafting table. Hand sketch first, AI render second — the judgment stays human.","Work in progress. Measure twice, prompt once."],U:["The blueprint wall. Blueprints: the original structured output.","Every building on this street was a drawing here first."],Q:["La Cocina's storefront. The awning alone raises the block's property value.","Smell that? That's Rosa's consommé calling."],J:["A jacaranda. The city plants them; the city argues about the petals.","Jacaranda shade. Free, and better than any meeting room."]}
 },
 es:{
  in1:"Meridian Labs necesita un héroe de la entrega con IA. Al líder anterior se le ocurrió hacer fine-tuning de algo que no debía y nunca se le volvió a ver.",
  in2:"La oficina es un mundo. Recórrela — pasillos, la cocina, las oficinas de la esquina. Los compañeros con ❗ tienen misiones; acércate y habla, en el orden que quieras. Algunas decisiones abren decisiones de seguimiento.",
  in3:"Cada decisión queda en tu expediente — al primer intento, al segundo o al tercero. La que sale mal te gana un veredicto y otra vuelta; la misión sigue abierta hasta que le atines, y aquí nunca se te quita nada de lo que ya levantaste. Ese expediente se vuelve un reporte de verdad, para llevártelo. Escalera: Junior → Líder de Delivery → Líder Senior → Leyenda de la IA.",
  in4:"Elige tu clase:",
  classes:{architect:["El Arquitecto","Ves sistemas. Los diagramas de Meridian te temen."],diplomat:["El Diplomático","Bilingüe, imperturbable. Los CFO firman cosas cerca de ti."],operator:["El Operador","Tú entregas. Los logs de producción susurran tu nombre."]},
  crTitle:"Crea tu héroe",lbName:"Nombre",lbOutfit:"Atuendo",lbShirt:"Camisa / saco",lbSkin:"Tono de piel",lbHairC:"Color de pelo",lbHairS:"Estilo de pelo",begin:"Fichar",
  outfits:[["casual","Casual"],["formal","Formal 👔"]],styles:[["cap","Corto"],["long","Largo"],["curly","Rizado"],["buzz","Rapado"],["spiky","Puntas"],["pony","Coleta"],["afro","Afro"],["mohawk","Cresta"],["braids","Trenzas"],["flat","Corte plano"],["buns","Chonguitos"],["edgar","Edgar"],["fade","Degradado"],["mullet","Mullet"],["broccoli","Brócoli"],["bald","Sin pelo"]],
  worldTag:"Meridian HQ · busca los ❗",
  hintSwipe:"Toca cualquier parte de la pantalla y arrastra para caminar · suelta para detenerte · ⚙️ para cambiar controles.",
  hintJoy:"Joystick o flechas para moverte · acércate a un compañero con ❗ y habla · ⚙️ para cambiar controles.",
  hintPad:"Cruceta o flechas para moverte · acércate a un compañero con ❗ y habla · ⚙️ para cambiar controles.",
  drwCtl:"🎮 Controles",drwLook:"🎨 Imagen",drwSound:"🔊 Sonido",drwGame:"⚙️ Juego",
  setTitle:"Ajustes",lbCtl:"Controles de movimiento",swipeB:"👆 Deslizar",joyB:"🕹️ Joystick",padB:"✛ Cruceta",lbLang:"Idioma",lbAdm:"Modo admin — toca casillas para remodelar la oficina",admOff:"Apagado",admOn:"🛠️ Activo",openLab:"📝 Laboratorio de textos",closeSet:"Listo",
  brushes:["Piso","Pared","Escritorio","Planta","Tapete","Puerta","Mesa","Refri","Estufa","Persona"],
  nmTitle:"Nuevo personaje",nmLb:"Ponles nombre — algunos nombres traen magia",nmOk:"✨ Crear",nmCancel:"Cancelar",
  npcMade:n=>n+" se mudó al barrio.",npcGone:"Se mudó a otra parte.",npcFull:"El barrio está lleno (máx. 12 amigos).",
  nmEditTitle:"Editar personaje",nmSave:"💾 Guardar",nmLook:"🎲 Otro look",nmOut:"📦 Mudanza",npcSaved:"Actualizado.",npcLook:"¡Look nuevo!",npcLease:"Tienen contrato — los vecinos originales se quedan.",
  chill:["Buen día para estar parado justo aquí.","No estorbo. SOY el camino.","El tranvía llegó tarde una vez. Una.",
   "Dicen que el perro de la oficina lleva mejor agenda que yo.","Aquí, vibrando. Es todo un oficio si lo haces bien.",
   "Las jacarandas solo florecen así cuando la semana va bien."],
  growthUp:"🏗️ ¡Avance! La obra de enfrente va tomando forma.",
  pigeon:["Curucucú.","La paloma juzga tu técnica para cruzar.","Estaba aquí antes que la ciudad. Seguirá después."],
  loro:["¡Ándale, jefe!","Lorenzo supervisa. Lorenzo aprueba.","¡Qué bonito trabajo!"],
  gato:["Mrrrp. El gato callejero lo permite.","Una oreja se mueve. Has sido reconocido.","Alguien le da sobras de tamal. Aquí manda el gato."],
  mariposa:["Se posa en una flor, solo para ti.","Alas como papel picado.","Da una vuelta lenta alrededor de tu cabeza. Bendecido."],
  colibri:["Se queda flotando a un brazo de ti, inspeccionándote. Apruebas.","Un helicopterito esmeralda con opiniones.","Doña Rosa dice que la visita de un colibrí anuncia buenas noticias."],
  tlTitle:"Laboratorio de textos",tlHint:"Edita nombres, títulos de misiones y frases de choque (JSON). Aplica al idioma actual.",tlApply:"Guardar",tlClose:"Cerrar",tlOk:"Textos actualizados.",tlErr:"Ese JSON no se pudo leer — no cambió nada.",
  levels:["Junior","Líder de Delivery","Líder Senior","LEYENDA DE LA IA"],
  quest:"Misión",followup:" · seguimiento",codexLb:"📜 Códice",
  okH:"⚔️ MISIÓN CUMPLIDA",midH:"🟡 ENTREGADO CON INCIDENTES",badH:"💔 RESBALÓN — tu reputación sufre",
  lvlUp:"⬆ SUBISTE DE NIVEL — ahora eres ",
  nextBack:"Volver a la oficina",nextEnd:"Reclama tu título",nextDoom:"Enfrenta las consecuencias",
  talkPre:"💬 ",
  tut1:"Este eres tú. Muévete con el joystick o las flechas.",tut2:"Escritorios, plantas y paredes solo bloquean — los compañeros con ❗ tienen misiones. Acércate y habla.",
  admToast:"Admin activado. Elige un pincel y toca casillas. Un gran poder conlleva la capacidad de encerrarte a ti mismo.",
  undoLb:"Deshacer",undoToast:"Edición deshecha.",undoEmpty:"Nada que deshacer.",
  tlFindPh:"Buscar texto…",tlNoHit:"Sin coincidencias.",
  dog:["¡Guau!","Frederick aprueba.","Frederick te pastorea de vuelta al trabajo."],
  treatLb:"🦴 Premio a Frederick",fredHeart:"Frederick: ❤",
  petCat:"🐾 Acariciar a Canela",petPig:"🐾 Saludar a Paloma",petLoro:"🦜 Saludar a Lorenzo",petGato:"🐾 Acariciar al gato callejero",petFly:"🦋 Observar la mariposa",petColi:"🌺 Observar al colibrí",
  fredUnlock:"Frederick ya confía en ti… y tiene papeleo. 🐾 Misión secreta desbloqueada — dale otro premio para abrirla.",
  carePackToast:"📦 Nuevo en ⚙️ → Exportar: el kit de cuidados de Frederick — su ficha + recordatorios, listos para tu propia mascota.",
  fredDoneToast:"🎀 Mod desbloqueado: el pañuelo rojo de Frederick.",
  locs:{ta:"Taller Herrera",pa:"Panadería La Espiga",li:"Limpieza Velázquez",no:"Nolasco Tax & Notario",hq:"Meridian HQ",f2:"Piso 2 · Tu oficina",st:"Calle Meridian",lc:"La Cocina",lo:"La Obra · Estudio",ex:"Calle Dos · Cuadra de expansión",me:"El Mercado Robles",pk:"El Parque 🌈"},
  chat:{beto:["Colamos, fraguamos, y nos movemos a la siguiente. Don Güero manda saludos.","Pregúntame en dos semanas, primo. Lo que esté detrás de esa cerca va a ser un edificio."],
        kike:["Muros derechos, prompts derechos — la misma disciplina.","La IA hizo el despiece de materiales. Revisé cada línea. Ya somos amigos."],
        mari:["Desde la grúa se ve el plan completo de Güero.","La IA ordena los izajes — peso, viento, orden. Suavecito todo el día."],
        chava:["El chile es el botón más rápido, güey. El que puso la carne cuatro pantallas adentro nunca se paró en esta fila.","Doña Chelo dice que rompí los números. Yo digo que los números me rompieron a mí.","Frijol se lleva los recortes. Frijol no ha trabajado ni un día."]},
  arrive:{ta:"Taller Herrera. Huele a balatas y a café.",pa:"La Espiga. Los hornos llevan prendidos desde las cuatro.",li:"Limpieza Velázquez. El piso está mojado. Siempre está mojado.",no:"Nolasco Tax & Notario, arriba. Tome su turno.",hq:"Meridian HQ.",f2:"Piso 2. Luz del norte, la pared donde va tu trabajo, y la máquina del que se fue, todavía con la sesión abierta.",st:"Nivel de calle. Cuidado con el cruce.",lc:"La Cocina — huele a consomé y a oportunidad.",lo:"El estudio de La Obra — tú ayudaste a construirlo. Cada dibujo de aquí se vuelve un edificio.",ex:"Calle Dos — el pueblo crece al este. Aquí se organiza la cuadrilla; lo que están construyendo siempre está en otra parte.",me:"El Mercado Robles — cilantro, cumbia en el radio y un negocio con opiniones.",pk:"El Parque — pasto, río y puente arcoíris. Aquí no hay reloj."},
  trolley:{title:"🚋 Tranvía del Barrio",note:"La línea MQT — cada distrito, un solo viaje. ¿A dónde vamos?",here:"estás aquí",soon:"Barrio Norte — próximamente",close:"Quedarme aquí"},
  cat:["Mrrp.","Canela parpadea despacio. Estás aceptado.","La inspectora de salubridad no sabe de Canela. Que siga así."],
  endGo:"▶ Salir a la calle",
  waitingAt:p=>"Alguien en "+p+" tiene algo que decirte.",
  weekTwoToast:"Ocho de la mañana. Doña Chelo abre la reja del lote suroeste — y la deja abierta. Atrás de ti tampoco se cierra nada.",
  mepi1:"Sábado, hora de cerrar. Doña Chelo cuenta la caja dos veces, como lo ha hecho por treinta años, y esta vez el número coincide con lo que la pantalla dijo toda la semana. “No me construiste un robot,” dice. “Me construiste un martes en el que puedo confiar.” Frijol duerme sobre la báscula. Afuera, alguien está tendiendo vía. Antes de que salgas ya está en el teléfono de la pared. «Tacho. Me dijo que dejara de pagarle por algo. Mándale lo peor que tengas.»",
  mepi2:"Sábado, hora de cerrar. Algo pegó, algo Nando volvió a hacer a mano sin decir nada. Doña Chelo se encoge de hombros. “La mitad sirve. Es más que el anterior.” Escribe tu nombre en la pared junto a la caja, al lado del permiso — debajo de un nombre con letra más vieja que todavía no reconoces. En el teléfono de la pared, más tarde: «Tacho. La mitad de lo que hizo sirve. Es más que el anterior.»",
  mepi3:"Sábado, hora de cerrar. El mercado te sobrevivió. Casi toda la lista sigue siendo lista, y el piloto es una carpeta que nadie abre — pero Doña Chelo igual te da una bolsa de pan dulce. “Vuelve cuando lo hayas pensado.” La puerta no se cierra con llave detrás de ti. Una semana después le habla a Tacho y le dice una sola cosa: «Es honesto con lo que no sabe. Empieza por ahí.»",
  expBtn:"📤 Exportar (beta)",expTitle:"Exportar (beta)",
  expHint:"Esqueleto v1 — tus datos de juego como JSON, listos para copiar. Futuro: documentos tipados desde trabajo real (reporte de decisiones), envío por correo, exportar conversaciones.",
  expCopy:"Copiar",expCopied:"Copiado al portapapeles.",
  exTabJson:"Datos de juego",exTabCare:"🐾 Kit de cuidados",exIcs:"📅 Recordatorios (.ics)",
  exTabRep:"📄 Reporte de decisiones",exDl:"⬇️ Descargar (.md)",
  repHint:"Cada decisión que tomaste, redactada como pieza de portafolio — la pregunta, tu respuesta, el concepto que puso a prueba y por qué funcionó. Cópialo, o descarga el Markdown y entrégalo en una entrevista.",
  repHead:(n,lv,x,mx,he,dt)=>`# Reporte de Decisiones — ${n}

*Meridian Quest · criterio bajo presión · ${dt}*

**Nivel:** ${lv}  ·  **XP:** ${x}/${mx}  ·  **Calificación:** ${he}`,
  repSum:(d,q,pct)=>`**${d} decisiones en ${q} misiones — ${pct}% resueltas al primer intento.**`,
  repEmpty:"Aún no hay decisiones registradas. Responde una misión y este reporte se escribe solo.",
  repRole:(c,q,pct)=>`${c} ${c===1?"decisión":"decisiones"} en ${q} ${q===1?"misión":"misiones"} · ${pct}% al primer intento`,
  repL:{roles:"Roles practicados",side:"Misión personal",
    question:"Pregunta",call:"Tu decisión",verdict:"Veredicto",why:"Por qué",
    ok:"✅ Buena decisión",mid:"◐ Crédito parcial",bad:"✕ Fallo",
    advanced:"Correcto — avanzaste al seguimiento.",
    concepts:"Conceptos practicados",attempts:"intentos",attempt:"intento",
    foot:"Generado por Meridian Quest — un gimnasio de práctica, no un certificado."},
  careHint:"El sistema de operaciones de Frederick como entregable real — copia la ficha, descarga los recordatorios recurrentes y pon los datos de tu propia mascota.",
  carePack:(n,tr,p)=>`# 🐾 KIT DE CUIDADOS DE ${p.n.toUpperCase()}
A cargo de ${n} · Meridian Labs
Una sola fuente de verdad para una gran mascota.

## Diario
- ${p.am}  Desayuno
- Paseo matutino — 20 min
- ${p.pm}  Cena
- Paseo vespertino — 20 min
- Premios: máx. 3 al día (premios dados a Frederick en el juego: ${tr})

## Recurrente — si se repite, lleva recordatorio
- Pulgas/garrapatas + desparasitante ... mensual, el día 1
- Peluquería ........................... cada 8 semanas
- Pesaje ............................... cada 3 meses
- Chequeo veterinario + vacunas ........ anual (agenda con 2 semanas de anticipación)
- Día de lote de contenido ............. mensual: la IA redacta, un humano aprueba

## Reglas de la casa (según lo decidido en la misión)
1. Esta ficha es la única fuente de verdad — no el refri, no la cabeza de tres personas.
2. La memoria no es un sistema — cada ciclo de arriba vive en un calendario compartido (ve el .ics).
3. Una lista compartida; quien dé de comer, la marca.
4. Nada se publica como ${p.n} sin aprobación humana. ${p.n} no puede aprobar. ${p.n} es una gran mascota.`,
  careEvents:pn=>["🐾 Pulgas/garrapatas + desparasitante — "+pn,"🐾 Peluquería — "+pn,"🐾 Pesaje — "+pn,"🐾 Chequeo veterinario + vacunas — "+pn,"📸 Día de contenido de "+pn],
  petPh:"Nombre de la mascota",
  wdTitle:"🧵 El Drop de Xochi",wdNote:"Recién salido del tech pack — viste al barrio. Frederick ronda el HQ; Canela reina en La Cocina. Los cambios se guardan al instante.",
  wdBandana:"Bandana",wdCollar:"Collar",wdCape:"Capa",
  wdUnlockToast:"🧵 Vestidor desbloqueado — en ⚙️ Ajustes, o con Xochi cuando venzas su misión.",
  wdBtn:"🧵 Vestidor",
  tpBtn:"🎫 Pase del Tranvía",tpTitle:"🎫 Pase del Tranvía",
  tpNote:"Tu partida, sellada como pase de tranvía. Escanea el código con la cámara de tu otro dispositivo, o comparte el pase — al abordar allá siempre se pregunta primero.",
  tpShare:"📤 Compartir pase",tpCopy:"🔗 Copiar enlace",tpCopied:"Enlace del pase copiado.",
  tpFoundLb:"🎫 Pase del Tranvía encontrado",
  tpFoundTx:(n,x,d,q)=>`${n} llegó en el tranvía — ${x} XP, ${d}/${q} misiones.`,
  tpReplace:n=>`Abordar reemplaza la partida de este dispositivo (${n}).`,
  tpBoard:"🎫 Abordar con esta partida",tpSkip:"Conservar la partida de este dispositivo",
  mpBtn:"🌐 Multijugador 🚧",mpTitle:"🌐 Multijugador",
  mpNote:"🚧 En construcción. La cuadrilla del MQT está tendiendo vías hacia Barrio Norte — un día otros consultores rondarán estas calles contigo. Por ahora, la oficina es toda tuya. (El casco no se quita hasta que abra la línea.)",
  lbTheme:"Tema de color",
  updToast:"¡actualizado! Hay cosas nuevas.",lbSeason:"Temporada",seasonAuto:"📅 Según el calendario",seasonOff:"Todo el año",lbCam:"Cámara",camTop:"🗺️ Cenital",camFront:"🏘 Frontal 2.5D",camIso:"◆ Isométrica",cam3d:"⛰ 3D",
  ballLb:"🎾 Lanza la pelota",ballNoRoom:"No hay espacio para lanzar aquí.",
  fetchYes:["¡Entregada! Un poco babeada, totalmente perfecta.","La trae como si fuera toda su carrera.","Recuperada. La cola dice que otra vez."],
  fetchNo:["Mira la pelota. Te mira a ti. Se sienta.","La pelota rueda. Él decidió que es problema de la pelota.","Hoy no. Es un perro de principios."],
  howl:"AUUUUUU…",
  beagleTreat:["¡Un premio! La cola despega.","Lo acepta con cuidado, como un caballero.","Crunch. Eres su persona favorita por una hora.","Recargado — ahorita te trae lo que sea."],
  cmdLb:"🎓 Comandos",
  cmdSit:"Siéntate",cmdDown:"Échate",cmdStay:"Quieto",cmdCome:"¡Ven!",cmdFollow:"Sígueme",
  cmdOkSit:"Se sienta. Un profesional.",cmdOkDown:"Echado. Totalmente desinflado.",
  cmdOkStay:"Se queda. Sus ojos nunca te dejan.",cmdOkCome:"Viene corriendo, orejas al vuelo.",
  cmdNo:["Te mira con un amor enorme y no hace nada.","Te oyó. Lo está considerando.","Una hoja era más interesante. Intenta otra vez."],
  cmdTrained:n=>`Entrenamiento +1 — ${n} lo hace cada vez mejor.`,
  followOn:"Trota a tu lado.",followOff:"Perro libre. Igual se queda cerca.",
  sniff:"El saludo ancestral, ejecutado correctamente.",
  chaseToast:"¡Zoomies! El parque aprueba.",
  dupDog:n=>`Ya hay un perro que se llama ${n} aquí.`,
  adoptBreed:"Raza",adoptColor:"Pelaje",
  breeds:{beagle:"🐶 Beagle",lab:"🦮 Labrador",chi:"🐕 Chihuahua"},
  renameLb:"✏️ Renombrar",renameAsk:"Un nuevo nombre para este buen perro:",renGo:"💾 Renombrar",
  renameDone:n=>`Ahora responde a ${n}. Al instante, porque es perro.`,
  rehomeLb:"🏡 Reubicar",
  rehomeDone:(n,f)=>`${n} se mudó con ${f}. En esta ciudad nadie se borra — visítalo cuando quieras.`,
  loveLb:"💗 Te quiero",
  loveLines:["Todo el cuerpo se le mueve. Lo sabe. Siempre lo ha sabido.","Recarga la cabeza en tu mano. Mensaje recibido.","Golpecito de cola. Parpadeo lento. Yo también te quiero, dice el perro."],
  leashLb:"🦮 ¡Al parque!",leashToast:n=>`${n} toma la correa con el hocico. Él conoce el camino — por el puente arcoíris.`,
  parkArrive:"🌈 ¡El Parque! Lanza la pelota, comparte un premio, escucha los aullidos — aquí no hay reloj.",
  bandLb:"🎀 Bandana",bandToast:"🎀 ¡Nuevo look!",bandOff:"🎀 Al natural.",
  adoptLb:"🏠 Adopta un perro",adoptAsk:"Nombra a tu nuevo mejor amigo:",adoptGo:"🐶 Bienvenido a casa",adoptX:"Todavía no",
  adoptDone:n=>`🐶 ${n} ya está en casa. El parque acaba de mejorar.`,
  parkFull:"El parque está lleno — cuatro perros ya son muchos perros.",
  parkTitle:"🌈 Un día en El Parque",
  parkSum:(f,t,h,d)=>`🎾 ${f} ${f===1?"entrega":"entregas"} · 🦴 ${t} ${t===1?"premio":"premios"} · 🐶 ${h} ${h===1?"aullido":"aullidos"} · 🕳 ${d} ${d===1?"hoyo":"hoyos"}`,
  parkLove:"Te quiere. Ese era todo el juego.",
  parkTeaser:"Un día Sonny tendrá su propio juego completo. Este parque es el adelanto.",
  parkClose:"↩ De vuelta a la ciudad",isoEdit:"Cambia la cámara a Cenital para editar casillas.",lbMusic:"Música",musOn:"🔊 Activa",musOff:"🔇 Silenciada",tunes:["🎼 Auto","Lo-fi","Campanas","Marimba","Atardecer"],
  themes:{meridian:"🏢 Meridian",forest:"🌿 Bosque",fairy:"🧚 Hada",sunset:"🌇 Atardecer",custom:"✨ Personalizado"},
  teOpen:"🎨 Editor de temas",teTitle:"🎨 Editor de temas",
  teFrom:"Parte de un preset (se clona en ✨ Personalizado)",teModeLb:"Variante en edición",
  teFix:"🪄 Auto-ajustar contraste",
  teSaved:"✨ Paleta guardada — elígela cuando quieras en Tema de color.",tePalsLb:"Paletas guardadas",teNamePh:"Nombre de la paleta",palFull:"El ropero está lleno (8 paletas) — saca una primero.",palNames:{meridian:"Meridian",forest:"Bosque",fairy:"Hada",sunset:"Atardecer"},teFixed:"🪄 Colores de texto ajustados hasta que cada par pasa la auditoría de contraste.",
  retryNote:"❗ Esta sigue abierta — vuelve y toma la mejor decisión.",
  retryNoteFred:"🦴 Frederick reabrirá la carpeta por otro premio.",
  mapTitle:"Mapa del pueblo",vmF2:"Piso 2",vmHQ:"Meridian HQ",vmSt:"Calle Meridian",vmLc:"La Cocina 🌶️",
  vmSite0:"🚧 Obra en construcción",vmSite2:"La Obra · Estudio 📐",vmPlots:"Lotes reservados — El Mercado y más",vmHere:"◉ estás aquí",
  goTitle:"🕯️ El piso dejó de confiar en ti",
  goEpi:"Priya te encuentra en el estacionamiento. «Tres malas decisiones y el piso dejó de confiar en ti. Eso es la semana — no es el trabajo.» Le da un golpecito a la carpeta que trae bajo el brazo. «Aquí adentro no se cerró nada. Mismo escritorio el lunes, y esta vez ya leíste el Códice.»",
  mgoEpi:"Sábado. Doña Chelo te da una bolsa de pan dulce y no te pide las llaves. «Aprendiste en mi piso. Para eso está el piso.» Lo que terminaste, el mercado se lo queda. Lo que no, sigue ahí en el mostrador, en una carpeta con tu letra, y la reja abre a las siete como siempre.",
  endStay:"↩ De vuelta a la ciudad",
  endStayToast:"La ciudad es tuya para caminarla. Lo que siga abierto, abierto se queda.",
  /* Las cuatro puertas — the four districts' Saturdays, their next-lot toasts, their burnouts (Nacho, 2026-09-02) */
  tallerToast:"Ocho de la mañana. La cortina del lote sureste está a medio subir y hay un Caprice en la banqueta. Don Tacho está al teléfono con Doña Chelo, y no se ve contento. Atrás de ti no se cierra nada.",
  tepi1:"Sábado, seis de la tarde. El libro está en la repisa junto a los manuales de Tacho, con el lomo hacia afuera, cerrado. Yesenia se va a las seis por primera vez en cuatro años y Tacho lo dice en voz alta, que viniendo de él es desfile. Moy está en el mostrador enseñándole la entrada de carros al chavo de la llantera. Tacho te da una llave de la puerta de al lado — «para cuando abra el tranvía y necesites dónde sentarte» — y levanta el teléfono del taller antes de que salgas del lote. «Licha. El de las computadoras. No me vendió nada. Pregúntale qué tiras.» Tuerca duerme sobre el cofre del Caprice. «Esa es Tuerca. Ya vive aquí. Yo no lo decidí.»",
  tepi2:"Sábado, seis de la tarde. La mitad pegó. Yesenia todavía lleva el libro — nomás para los trabajos que aún no le confía al sistema, y el montón se adelgaza cada semana. Tacho se limpia las manos y te suelta la frase más cierta de todo el edificio: «No me vendiste nada. Por eso te dejé quedarte.» El lunes le habla a Licha y le dice menos que eso. Tuerca de todos modos ya se subió al Caprice; a ella tampoco le preguntaron.",
  tepi3:"Sábado, seis de la tarde. El asistente de entrada está apagado y el libro está exactamente igual de grueso. Nada se rompió, nada se quemó, y Tacho es amable, que es peor y mejor que enojado: «Viniste, miraste, y dijiste la verdad de lo que no sabías. La mayoría miente en los primeros diez minutos.» Moy te acompaña a la reja y te pregunta, bajito, si debería dejar de usar lo del teléfono. Le dices que no. Le dices qué revisar. Una semana después Tacho le habla a Licha y dice una sola frase de ti; es justa. Tuerca se muda de todos modos.",
  tgoEpi:"Sábado. Tacho no te quita la llave de la puerta de al lado, porque nunca te la dio. «Aprendiste en mi piso. Para eso son los pisos.» El libro sigue en el mostrador con una hoja con tu letra, y la cortina sube a las siete.",
  espigaToast:"Cinco de la mañana en Calle Dos. Hay luz en el lote del poniente y los hornos ya están calientes — a Doña Licha le llegó una llamada. Atrás de ti no se cierra nada.",
  eepi1:"Sábado, hora de cerrar. Dos conchas en la última charola, nada en el bote de la merma, nadie se fue sin pan desde el martes. Doña Licha prende la hoja arriba del horno junto a los pares con su propia letra y te da una rosca en septiembre. «Para el camino, vecino. Ya sé en qué mes estamos.» Tito está dormido — dormido de verdad, a una hora decente, en otra parte. Entra la cuadrilla de Vero a trapear y Licha lo dice por encima del mostrador, sin teléfono: «Vero. Este sí cuenta. Dale tu peor cuadrilla.» Bolillo duerme en el bote de la harina. Nadie lo ha podido sacar de ahí nunca.",
  eepi2:"Sábado, hora de cerrar. La hoja corre; Tito le cree entre semana y a su panza los viernes, y la basura pesa menos que antes. Licha no ha prendido nada arriba del horno — los pares siguen en su cabeza — pero la tira de Sol ya tiene columna de hora, y los jueves aparece con la letra de Licha. Se lo dice a Vero por encima del mostrador, más corto: «Este cuenta. Pruébalo.» Bolillo está sentado en el bote de la harina con cara.",
  eepi3:"Sábado, hora de cerrar. La hoja está en un cajón y Tito volvió a decidir solo a las 3:45. Pero la tira de Sol tiene una columna que antes no tenía, y nadie le dijo que le parara. Licha te da una bolsa de pan de ayer — «Todavía sirve. Usted también, seguramente.» — y no le dice nada a Vero en una semana. Luego sí, una sola frase, por encima del mostrador, y es justa. Bolillo te sigue hasta la puerta y ahí se queda. Es su puerta.",
  egoEpi:"Sábado. Licha te da pan de ayer y no te pide la hoja de vuelta. «Aprendió en mi cocina. Para eso está el horno.» La tira sigue en el corcho con una columna con tu letra, y los hornos prenden a las cuatro.",
  velazquezToast:"Diez de la noche en Calle Dos. Hay una camioneta con cubeta de trapeador en el lote del oriente y alguien abre una puerta con la luz del celular. A Doña Vero la recomendaron por encima de un mostrador de panadería. Atrás de ti no se cierra nada.",
  vepi1:"Sábado. La cotización se fue el viernes con la palabra «cocina» en las doce hojas, a pluma. La hoja está arriba del tablero donde estaban los papelitos — tres números, el orden de la salida, y una línea firmada por Vero: esta app cuenta el trabajo; nunca vigila dónde estás. Chente la leyó dos veces y te dijo compañero una vez, sin querer, y no lo retiró. Vero te pone un sobre en la mano — la revisión del piloto — y dice: «Llévale esto a Nolasco. Él sí lee.» Pelusa duerme sobre la hoja de ruta. La hoja de ruta ya es impresa. Pelusa no se ha dado cuenta.",
  vepi2:"Sábado. Tres cuadrillas en la app, seis en el teléfono de Karla, y las llamadas de las 5:40 ya nomás caen los martes. El papel de Marta está en el mapa como la excepción que es. Vero mira la cotización y dice lo honesto: «Veinte personas es el año que entra. Nueve personas es ahorita, y nueve están mejor que antes.» Te manda con Nolasco con el sobre, y adentro una nota más corta. Pelusa va en la camioneta. Pelusa siempre va.",
  vepi3:"Sábado. La tableta volvió a la guantera y el tablero de Karla otra vez tiene papelitos. Pero uno dice «Marta no martes», y es la primera vez que alguien lo escribió. Vero no te manda con Nolasco con un sobre. Te manda con una frase, una semana después, y es justa: «Escuchó a Chente. Nadie escucha a Chente.» Pelusa te ve irte desde el tablero. No te juzga. Es gata; no le hace falta.",
  vgoEpi:"Sábado. Vero no te quita la tableta; nunca fue tuya. «Aprendiste en mi camioneta. Para eso es la camioneta.» La hoja sigue en el tablero con una línea con tu letra, y las cuadrillas salen a las diez.",
  nolascoToast:"Una escalera que sale de la Calle Principal, segunda puerta. Un letrero en dos idiomas, luz arriba, y una gata sentada exactamente donde iría el timbre. El Lic. Nolasco tiene un expediente con tu nombre. Él todo lo apunta. Atrás de ti no se cierra nada.",
  nepi1:"Sábado. Nolasco sella la última hoja de tu reporte y dice lo que significa el sello una vez más, porque se lo dice a todos: «Es un reconocimiento de firma. Firmaste frente a mí. No quiere decir que sea cierto.» Mira las cuatro cartas que están al lado. «Aunque sí lo es.» Te da la llave de un archivero — «Va para arriba. El expediente necesita cuerpo.» — y, porque él todo lo archiva, una nota para el perro: «Alguien debería avisarle a Frederick que va a haber ceremonia. Va a querer conducirla.» Timbre está sentada en la puerta, justo donde iría el timbre. La brincas. Te lo permite.",
  nepi2:"Sábado. Nolasco lee cada hoja antes de sellar nada, y eso tarda. Dos de tus entradas tienen la palabra prórroga en el margen, con su letra. «En estas pediste prórroga. Bien. La mayoría entrega una adivinanza.» El archivero igual sube; un cajón es tuyo para llenarlo. Timbre está en la escalera. Estaba en la escalera antes que la escalera.",
  nepi3:"Sábado. Nolasco lo lee todo y te dice lo más largo que alguien te ha dicho en el barrio, y nada de eso es cruel: el letrero, el sobrino, el desconocido — lo que cada uno le habría costado a una familia, y lo que hiciste la segunda vez. «Yo no califico gente, colega. La archivo. Este va en el cajón que dice abierto.» El archivero sube de todos modos, con un cajón vacío y tu nombre. Timbre te acompaña escaleras abajo. No lo hace por todos; no lo hace por nadie.",
  ngoEpi:"Sábado. Nolasco no te quita el expediente; nunca fue suyo. «Aprendiste en mi despacho. Para eso es un despacho.» La hoja sigue en el escritorio de Bere con una línea con tu letra, y la recepción abre a las nueve.",
  lastToast:"Esta noche no abre nada más. Bajando la escalera se alcanza a oír desde el norte: el último tramo cayendo al suelo, y alguien discutiendo por unas sillas plegables.",
  replayArm:"⚠️ Toca otra vez para borrar todo",
  endScore:(x,m,h)=>`${x}/${m} XP · ${h}/3 corazones intactos`,
  endGrade:(x,m,g)=>`${x}/${m} XP · ${g}`,
  grades:["la libraste","buen trabajo","impecable — al primer intento, casi siempre"],
  lbStakes:"Riesgo (admin)",stkNone:"Ninguno",stkHearts:"❤ Corazones",
  stkToast:m=>m==="hearts"?"Corazones encendidos. Una mala decisión cuesta uno — nada más.":"Corazones apagados. No hay nada que perder salvo la calificación.",goScore:(x,d,n)=>`${x} XP · ${d}/${n} misiones completadas`,
  epi1:"Viernes, 6pm. La VP se pone de pie cuando entras. «Semana impecable — y caminaste tu propio camino. El programa de agentes es tuyo.» Sales por el camino largo, pasando por la barda donde Nacho traza con carbón el contorno de una cuadra que todavía no existe.",
  epi2:"Viernes, 6pm. «Buena semana», dice la VP. «Se entregaron algunos incidentes, pero el piso fue tuyo.» Priya asiente cuando sales. La Semana Dos se acerca.",
  epi3:"Viernes, 6pm. Sobreviviste — apenas. La VP desliza el Códice de vuelta por la mesa: «Estudia. Todo lo que no contestaste sigue ahí esperándote. Eso no es castigo, eso es un martes.»",
  replay:"Nueva partida +",replayToast:n=>`De vuelta, ${n}. Misma oficina, héroe con más calle.`,
  contBtn:(n,x,d)=>`▶ Continuar como ${n} — ${x} XP, ${d}/${QES.length} misiones`,
  langQuick:"🌐 English",
  flavor:{"▭":["Papel en blanco, ya puesto. Todavía nadie se ha ganado este lugar."],
    "▤":["Un juego de hojas engrapadas, bien planas. Tuyas — acércate y léelas."],
    "□":["Tus cajas. Con cinta, rotuladas con tu letra, todavía donde las dejaron."],
    "|":["Tres vidrios de luz del norte. El lote de atrás, la salida vieja, y la línea donde va a pasar el tranvía."],
    "=":["Bloque pintado. Lo pintó Tacho, mal, a propósito."],"6":["El Caprice de Tacho. No te recargues. Él se entera."],"0":["Una pila de llantas. La refacción de alguien, el problema de alguien."],"7":["La rampa. Un coche en el aire es un coche al que ya escucharon."],"8":["La caja de herramientas. Cada cajón tiene su lugar y cada lugar su cajón."],"&":["La Espiga. Conchas en la vitrina desde las seis."],"!":["Limpieza Velázquez. Más limpio que tu cocina."],"▣":["El horno de piso. Doscientos treinta grados de paciencia."],"▯":["Un archivero. El año entero de alguien en un cajón."],"⊔":["Una silla de visita. Para quien necesite sentarse a platicar."],"○":["La cama del perro. No es para ti."],D:["Solo un escritorio. El monitor te juzga igual.","El escritorio de un colega. Su kombucha, sus reglas."],K:["La barra de café. Tierra sagrada.","La cafetera. Ha visto cosas."],P:["Una planta en maceta. Hace lo que puede.","El ficus de la oficina. Moral estructural."],"#":["Una pared. Argumento sólido.","Eso es una pared. Hasta las leyendas respetan las paredes."],"+":["Una puerta. Se abre caminando a través de ella. Tecnología.","Puerta detectada. Puedes pasar."],B:["La fachada del edificio. Sólida. Corporativa.","Ladrillo. Estaba aquí antes que tú y seguirá después."],F:["Cerca de obra. Casco obligatorio más allá."],G:["Vigas de acero. El futuro tiene andamios."],C:["Un cono de tráfico. Respétalo."],X:["🚧 Un lote vacío con su cerca y un permiso pegado en el poste. Todos los negocios de esta calle empezaron exactamente así."],T:["Una mesa del comedor. El mantel no es negociable.","Reservada. Probablemente para Canela."],W:["El cuarto frío. El pronóstico de Chuy está pegado ahí. Es ley.","Almacén frío. Donde los márgenes viven o mueren."],V:["La estufa. Seis quemadores de diplomacia de consomé.","Caliente. Dominio de Chuy. Pregunta antes de tocar."],A:["Una mesa de dibujo. Primero el boceto a mano, luego el render con IA — el criterio sigue siendo humano.","Trabajo en curso. Mide dos veces, promptea una."],U:["El muro de planos. Los planos: la salida estructurada original.","Cada edificio de esta calle fue primero un dibujo aquí."],Q:["La fachada de La Cocina. El toldo solito sube la plusvalía de la cuadra.","¿Hueles eso? Es el consomé de Rosa llamándote."],J:["Una jacaranda. La ciudad las planta; la ciudad discute por los pétalos.","Sombra de jacaranda. Gratis, y mejor que cualquier sala de juntas."]}
 }
};
