/* Meridian Quest content pack — UI strings, every player-facing line, EN+ES in lockstep. */
const UI={
 en:{
  in1:"Meridian Labs needs an AI delivery hero. The old lead fine-tuned something he shouldn't have and was never seen again.",
  in2:"The office is a world. Roam it — hallways, the kitchen, the corner offices. Coworkers with a ❗ have quests; walk up and talk, in any order. Some decisions open follow-up decisions.",
  in3:"Three reputation hearts. Bad calls cost one; mediocre calls earn half XP — and either way the quest stays open until you make the right call. Lose all three hearts and the week resets. Ladder: Junior → Delivery Lead → Senior Lead → AI Legend.",
  in4:"Choose your class:",
  classes:{architect:["The Architect","You see systems. Meridian's diagrams fear you."],diplomat:["The Diplomat","Bilingual, unflappable. CFOs sign things near you."],operator:["The Operator","You ship. Production logs whisper your name."]},
  crTitle:"Create your hero",lbName:"Name",lbOutfit:"Outfit",lbShirt:"Shirt / jacket",lbSkin:"Skin tone",lbHairC:"Hair color",lbHairS:"Hair style",begin:"Badge in",
  outfits:[["casual","Casual"],["formal","Formal 👔"]],styles:[["cap","Short"],["long","Long"],["curly","Curly"],["buzz","Buzz"],["spiky","Spiky"],["pony","Ponytail"],["afro","Afro"],["mohawk","Mohawk"],["braids","Braids"],["flat","Flat top"],["buns","Buns"],["edgar","Edgar"],["fade","Taper fade"],["mullet","Mullet"],["broccoli","Broccoli"],["bald","Bald"]],
  worldTag:"Meridian HQ · find the ❗",
  hintSwipe:"Touch anywhere on the screen and drag to walk · release to stop · ⚙️ to switch controls.",
  hintJoy:"Joystick or arrow keys to roam · walk up to a ❗ coworker and Talk · ⚙️ to switch controls.",
  hintPad:"D-pad or arrow keys to roam · walk up to a ❗ coworker and Talk · ⚙️ to switch controls.",
  setTitle:"Settings",lbCtl:"Movement controls",swipeB:"👆 Swipe",joyB:"🕹️ Joystick",padB:"✛ D-pad",lbLang:"Language",lbAdm:"Admin mode — touch tiles to reshape the office",admOff:"Off",admOn:"🛠️ On",openLab:"📝 Text lab",closeSet:"Done",
  brushes:["Floor","Wall","Desk","Plant","Rug","Door","Table","Fridge","Stove","Character"],
  nmTitle:"New character",nmLb:"Name them — some names carry magic",nmOk:"✨ Create",nmCancel:"Cancel",
  npcMade:n=>n+" moved into the barrio.",npcGone:"They moved away.",npcFull:"The barrio is full (12 friends max).",
  nmEditTitle:"Edit character",nmSave:"💾 Save",nmLook:"🎲 New look",nmOut:"📦 Move out",npcSaved:"Updated.",npcLook:"New look!",npcLease:"They have a lease — the original townsfolk stay.",
  chill:["Nice day for standing exactly here.","I'm not in the way. I AM the way.","The trolley was late once. Once.",
   "I heard the office dog keeps a better calendar than me.","Just vibing. It's a whole job if you do it right.",
   "The jacarandas only bloom like this when the week's going well."],
  obraUp:"🏗️ Progress! The site across the street is taking shape.",
  pigeon:["Coo.","The pigeon judges your crosswalk technique.","She was here before the city. She'll be here after."],
  loro:["¡Ándale, jefe!","Lorenzo supervises. Lorenzo approves.","¡Qué bonito trabajo!"],
  gato:["Mrrrp. The street cat allows it.","One ear flicks. You have been acknowledged.","The crew feeds him tamale scraps. He runs this site."],
  mariposa:["It rests on a bloom, just for you.","Wings like papel picado.","It does one slow loop around your head. Blessed."],
  colibri:["It hovers an arm away, inspecting you. You pass.","A tiny emerald helicopter with opinions.","Doña Rosa says a colibrí visit means good news is coming."],
  tlTitle:"Text lab",tlHint:"Edit names, quest titles and bump lines (JSON). Applies to the current language.",tlApply:"Save",tlClose:"Close",tlOk:"Texts updated.",tlErr:"That JSON didn't parse — nothing changed.",
  levels:["Junior","Delivery Lead","Senior Lead","AI LEGEND"],
  quest:"Quest",followup:" · follow-up",codexLb:"📜 Codex",
  okH:"⚔️ QUEST COMPLETE",midH:"🟡 SHIPPED WITH INCIDENTS",badH:"💔 SLIP — reputation takes a hit",
  lvlUp:"⬆ LEVEL UP — you are now ",
  nextBack:"Back to the office",nextEnd:"Claim your title",nextDoom:"Face the consequences",
  talkPre:"💬 ",
  tut1:"This is you. Roam with the joystick or arrow keys.",tut2:"Desks, plants and walls just block you — coworkers with a ❗ have quests. Walk up and Talk.",
  admToast:"Admin on. Pick a brush, tap tiles. With great power comes the ability to wall yourself in.",
  undoLb:"Undo",undoToast:"Edit undone.",undoEmpty:"Nothing to undo.",
  tlFindPh:"Search text…",tlNoHit:"No match.",
  dog:["Woof!","Frederick approves.","Frederick is herding you back to work."],
  treatLb:"🦴 Treat Frederick",fredHeart:"Frederick: ❤",
  petCat:"🐾 Pet Canela",petPig:"🐾 Greet Paloma",petLoro:"🦜 Say hi to Lorenzo",petGato:"🐾 Pet the street cat",petFly:"🦋 Watch the butterfly",petColi:"🌺 Watch the colibrí",
  fredUnlock:"Frederick trusts you now… and he has paperwork. 🐾 Secret side quest unlocked — treat him again to open it.",
  carePackToast:"📦 New in ⚙️ → Export: Frederick's care pack — his sheet + reminders, ready for your own pet.",
  fredDoneToast:"🎀 Mod unlocked: Frederick's red bandana.",
  locs:{hq:"Meridian HQ",f2:"Floor 2 · Expansion",st:"Meridian Street",lc:"La Cocina",lo:"La Obra · Studio",ex:"Calle Dos · Expansion block",me:"El Mercado Robles",pk:"El Parque 🌈"},
  chat:{beto:["We pour El Mercado's slab Thursday. Don Güero says hi.","Two more weeks and this block gets groceries, primo."],
        kike:["Straight walls, straight prompts — same discipline.","The AI did the material takeoff. I checked every line. We're friends now."],
        mari:["From the crane you can see Güero's whole plan.","The lift schedule is AI-sorted — weight, wind, order. Smooth all day."],
        chava:["Chile. Everything is chile. It's the fastest button, güey.","Doña Chelo says I broke the numbers. I say the numbers broke me first.","Frijol gets the trimmings. Frijol has never worked a day."]},
  arrive:{hq:"Meridian HQ.",f2:"Floor 2 — expansion space. Quiet up here… for now.",st:"Street level. Mind the crosswalk.",lc:"La Cocina — smells like consommé and opportunity.",lo:"La Obra's studio — you helped build this. Every drawing here becomes a building.",ex:"Calle Dos — the town grows east. El Mercado is going up.",me:"El Mercado Robles — cilantro, cumbia on a radio, and a business with opinions.",pk:"El Parque — grass, river, rainbow bridge. No clock in here."},
  trolley:{title:"🚋 Barrio Trolley",note:"The MQT line — every district, one hop. Where to, consultant?",here:"you are here",soon:"Barrio Norte — coming soon",close:"Stay here"},
  cat:["Mrrp.","Canela blinks slowly. You are accepted.","The health inspector doesn't know about Canela. Keep it that way."],
  endGo:"▶ Monday — Week Two",
  weekTwoToast:"Monday, 8am. Doña Chelo is unlocking the gate on the southwest lot. Three hearts, fresh week.",
  mepi1:"Saturday, closing time. Doña Chelo counts the drawer twice, the way she has for thirty years, and this time the number matches what the screen said all week. “You didn't build me a robot,” she says. “You built me a Tuesday I can trust.” Frijol sleeps on the scale. Roll credits.",
  mepi2:"Saturday, closing time. Some of it stuck, some of it Nando quietly went back to doing by hand. Doña Chelo shrugs. “Half of it works. That's more than the last guy.” She writes your name on the wall by the register, next to the permit. Roll credits.",
  mepi3:"Saturday, closing time. The mercado survived you. Chava still rings everything as chile, and the pilot is a folder nobody opens — but Doña Chelo hands you a bag of pan dulce anyway. “Come back when you've thought about it.” Roll credits.",
  expBtn:"📤 Export (beta)",expTitle:"Export (beta)",
  expHint:"Skeleton v1 — your play data as JSON, ready to copy. Future: typed documents from real work (decision report), email delivery, conversation export.",
  expCopy:"Copy",expCopied:"Copied to clipboard.",
  exTabJson:"Play data",exTabCare:"🐾 Care pack",exIcs:"📅 Reminders (.ics)",
  exTabRep:"📄 Decision report",exDl:"⬇️ Download (.md)",
  repHint:"Every call you made, written up as a portfolio piece — the question, your answer, the concept it tested, and why it landed. Copy it, or download the Markdown and hand it to a hiring manager.",
  repHead:(n,lv,x,mx,he,dt)=>`# Decision Report — ${n}

*Meridian Quest · judgment calls under pressure · ${dt}*

**Level:** ${lv}  ·  **XP:** ${x}/${mx}  ·  **Grade:** ${he}`,
  repSum:(d,q,pct)=>`**${d} decisions across ${q} quests — ${pct}% solved on the first attempt.**`,
  repEmpty:"No decisions recorded yet. Answer a quest and this report writes itself.",
  repRole:(c,q,pct)=>`${c} ${c===1?"decision":"decisions"} across ${q} ${q===1?"quest":"quests"} · ${pct}% first try`,
  repL:{roles:"Roles practiced",side:"Personal side quest",
    question:"Question",call:"Your call",verdict:"Verdict",why:"Why",
    ok:"✅ Solid call",mid:"◐ Partial credit",bad:"✕ Miss",
    advanced:"Correct — advanced to the follow-up.",
    concepts:"Concepts practiced",attempts:"attempts",attempt:"attempt",
    foot:"Generated by Meridian Quest — a practice gym, not a certificate."},
  careHint:"Frederick's ops system as a real deliverable — copy the sheet, download the recurring reminders, swap in your own pet's details.",
  carePack:(n,tr,p)=>`# 🐾 ${p.n.toUpperCase()}'S CARE PACK
Kept by ${n} · Meridian Labs
One source of truth for one very good pet.

## Daily
- ${p.am}  Breakfast
- Morning walk — 20 min
- ${p.pm}  Dinner
- Evening walk — 20 min
- Treats: 3/day max (in-game treats given to Frederick: ${tr})

## Recurring — if it repeats, it gets a reminder
- Flea/tick + heartworm ....... monthly, the 1st
- Grooming .................... every 8 weeks
- Weigh-in .................... every 3 months
- Vet checkup + vaccines ...... yearly (book 2 weeks ahead)
- Content batch day ........... monthly: AI drafts the captions, a human approves

## House rules (as decided in the quest)
1. This sheet is the single source of truth — not the fridge, not three people's heads.
2. Memory is not a system — every cycle above lives in a shared calendar (see the .ics).
3. One shared checklist; whoever does the feeding checks it off.
4. Nothing posts as ${p.n} without human approval. ${p.n} cannot approve. ${p.n} is a very good pet.`,
  careEvents:pn=>["🐾 Flea/tick + heartworm — "+pn,"🐾 Grooming — "+pn,"🐾 Weigh-in — "+pn,"🐾 Vet checkup + vaccines — "+pn,"📸 "+pn+" content batch day"],
  petPh:"Pet's name",
  wdTitle:"🧵 Xochi's Collar Drop",wdNote:"Fresh from the tech pack — dress the neighborhood. Frederick roams HQ; Canela holds court at La Cocina. Changes save instantly.",
  wdBandana:"Bandana",wdCollar:"Collar",wdCape:"Cape",
  wdUnlockToast:"🧵 Wardrobe unlocked — in ⚙️ Settings, or with Xochi once her quest is beaten.",
  wdBtn:"🧵 Wardrobe",
  tpBtn:"🎫 Trolley Pass",tpTitle:"🎫 Trolley Pass",
  tpNote:"Your save, stamped as a transit pass. Scan the code with your other device's camera, or share the pass to it — boarding over there always asks first.",
  tpShare:"📤 Share pass",tpCopy:"🔗 Copy link",tpCopied:"Pass link copied.",
  tpFoundLb:"🎫 Trolley Pass found",
  tpFoundTx:(n,x,d,q)=>`${n} rode in on the trolley — ${x} XP, ${d}/${q} quests.`,
  tpReplace:n=>`Boarding replaces this device's save (${n}).`,
  tpBoard:"🎫 Board with this save",tpSkip:"Keep this device's save",
  mpBtn:"🌐 Multiplayer 🚧",mpTitle:"🌐 Multiplayer",
  mpNote:"🚧 Under construction. The MQT crew is laying track to Barrio Norte — one day other consultants will roam these streets with you. For now, the office is all yours. (Hard hats stay on until the line opens.)",
  lbTheme:"Color theme",
  updToast:"updated! New stuff is in.",lbCam:"Camera",camTop:"🗺️ Top-down",camFront:"🏘 Front 2.5D",camIso:"◆ Isometric",cam3d:"⛰ 3D",
  ballLb:"🎾 Throw the ball",ballNoRoom:"No room to throw here.",
  fetchYes:["Delivered! Slightly slobbery, entirely perfect.","He brings it back like it's his whole career.","Retrieved. The tail says do it again."],
  fetchNo:["He looks at the ball. He looks at you. He sits.","The ball rolls. He has decided it is the ball's problem.","Not today. He is a dog of principle."],
  howl:"AWOOOOO…",
  beagleTreat:["A treat! The tail achieves liftoff.","He accepts it gently, like a gentleman.","Crunch. You are his favorite person for the next hour.","Fueled up — he'd fetch anything for you right now."],
  loveLb:"💗 I love you",
  loveLines:["His whole body wags. He knows. He's always known.","He presses his head into your hand. Message received.","Tail thump. Slow blink. I love you too, says the dog."],
  leashLb:"🦮 To the park!",leashToast:n=>`${n} takes the leash in his mouth. He knows the way — over the rainbow bridge.`,
  parkArrive:"🌈 El Parque! Throw the ball, share a treat, listen for howls — there is no clock here.",
  bandLb:"🎀 Bandana",bandToast:"🎀 New look!",bandOff:"🎀 Au naturel.",
  adoptLb:"🏠 Adopt a dog",adoptAsk:"Name your new best friend:",adoptGo:"🐶 Welcome home",adoptX:"Not yet",
  adoptDone:n=>`🐶 ${n} is home. The park just got better.`,
  parkFull:"The park is full — four dogs is already a lot of dogs.",
  parkTitle:"🌈 A day at El Parque",
  parkSum:(f,t,h,d)=>`🎾 ${f} ${f===1?"fetch":"fetches"} · 🦴 ${t} ${t===1?"treat":"treats"} · 🐶 ${h} ${h===1?"howl":"howls"} · 🕳 ${d} ${d===1?"hole":"holes"}`,
  parkLove:"He loves you. That was the whole game.",
  parkTeaser:"One day Sonny gets a whole game of his own. This park is the preview.",
  parkClose:"↩ Back to the city",isoEdit:"Switch the camera to Top-down to edit tiles.",lbMusic:"Music",musOn:"🔊 On",musOff:"🔇 Muted",tunes:["🎼 Auto","Lo-fi","Bells","Marimba","Dusk"],
  themes:{meridian:"🏢 Meridian",forest:"🌿 Forest",fairy:"🧚 Fairy",sunset:"🌇 Sunset",custom:"✨ Custom"},
  teOpen:"🎨 Theme editor",teTitle:"🎨 Theme editor",
  teFrom:"Start from a preset (clones it into ✨ Custom)",teModeLb:"Editing variant",
  teFix:"🪄 Auto-fix contrast",
  teSaved:"✨ Palette saved — pick it any time under Color theme.",tePalsLb:"Saved palettes",teNamePh:"Palette name",palFull:"The wardrobe is full (8 palettes) — evict one first.",palNames:{meridian:"Meridian",forest:"Forest",fairy:"Fairy",sunset:"Sunset"},teFixed:"🪄 Text colors nudged until every pair passes the contrast audit.",
  retryNote:"❗ This one stays open — come back and make the better call.",
  retryNoteFred:"🦴 Frederick will reopen the folder for another treat.",
  mapTitle:"Village map",vmF2:"Floor 2",vmHQ:"Meridian HQ",vmSt:"Meridian Street",vmLc:"La Cocina 🌶️",
  vmSite0:"🚧 Construction site",vmSite2:"La Obra · Studio 📐",vmPlots:"Reserved lots — El Mercado & more",vmHere:"◉ you are here",
  goTitle:"🕯️ The week got away from you",
  goEpi:"Priya finds you in the parking lot. “Three bad calls and the floor stopped trusting you. That's the week — it isn't the job.” The chapter closes where it stands: whatever you left unanswered stays unanswered, and it goes in the file. “Same desk Monday. This time you've read the Codex.”",
  mgoEpi:"Saturday. Doña Chelo takes the keys back with no hard feelings and a bag of pan dulce. “You learned on my floor. That's what a floor is for.” The mercado keeps what you finished and forgets the rest. Roll credits.",
  endStay:"↩ Back to the city",
  endStayToast:"The city is yours to walk. Nothing left to answer — for now.",
  replayArm:"⚠️ Tap again to erase everything",
  endScore:(x,m,h)=>`${x}/${m} XP · ${h}/3 hearts intact`,
  endGrade:(x,m,g)=>`${x}/${m} XP · ${g}`,
  grades:["scraped through","solid work","clean — first try, nearly every time"],
  lbStakes:"Stakes (admin)",stkNone:"None",stkHearts:"❤ Hearts",
  stkToast:m=>m==="hearts"?"Hearts on. Wrong calls cost one — nothing else.":"Hearts off. Nothing to lose but the grade.",goScore:(x,d,n)=>`${x} XP · ${d}/${n} quests completed`,
  epi1:"Friday, 6pm. The VP stands up when you enter. “Flawless week — and you walked your own path. The agents program is yours.” Roll credits — until Week Two.",
  epi2:"Friday, 6pm. “Strong week,” says the VP. “Some incidents shipped, but you owned the floor.” Priya nods on your way out. Week Two is coming.",
  epi3:"Friday, 6pm. You survived — barely. The VP slides the Codex back across the table: “Study. Run the week again. Meridian believes in second playthroughs.”",
  replay:"New game +",replayToast:n=>`Back at it, ${n}. Same office, wiser hero.`,
  contBtn:(n,x,d)=>`▶ Continue as ${n} — ${x} XP, ${d}/${QEN.length} quests`,
  langQuick:"🌐 Español",
  flavor:{D:["Just a desk. The monitor is judging you anyway.","A coworker's desk. Their kombucha, their rules."],K:["The coffee counter. Sacred ground.","The coffee machine. It has seen things."],P:["A potted plant. It's doing its best.","The office ficus. Load-bearing morale."],"#":["A wall. Solid argument.","That's a wall. Even AI Legends respect walls."],"+":["A door. It opens by walking through it. Technology.","Doorway detected. You may proceed."],B:["The building facade. Sturdy. Corporate.","Brick. It was here before you and will be here after."],F:["Construction fence. Hard hats beyond this point."],G:["Steel girders. The future has scaffolding."],C:["A traffic cone. Respect it."],X:["🚧 Under construction — La Cocina (restaurant), El Mercado (grocery), and La Obra (construction office) open here soon."],T:["A dining table. The tablecloth is non-negotiable.","Reserved. Probably for Canela."],W:["The walk-in fridge. Chuy's forecast is taped to it. It is law.","Cold storage. Where margins live or die."],V:["The stove. Six burners of consommé diplomacy.","Hot. Chuy's domain. Ask before touching."],A:["A drafting table. Hand sketch first, AI render second — the judgment stays human.","Work in progress. Measure twice, prompt once."],U:["The blueprint wall. Blueprints: the original structured output.","Every building on this street was a drawing here first."],Q:["La Cocina's storefront. The awning alone raises the block's property value.","Smell that? That's Rosa's consommé calling."],J:["A jacaranda. The city plants them; the city argues about the petals.","Jacaranda shade. Free, and better than any meeting room."]}
 },
 es:{
  in1:"Meridian Labs necesita un héroe de la entrega con IA. Al líder anterior se le ocurrió hacer fine-tuning de algo que no debía y nunca se le volvió a ver.",
  in2:"La oficina es un mundo. Recórrela — pasillos, la cocina, las oficinas de la esquina. Los compañeros con ❗ tienen misiones; acércate y habla, en el orden que quieras. Algunas decisiones abren decisiones de seguimiento.",
  in3:"Tres corazones de reputación. Las malas decisiones cuestan uno; las mediocres dan la mitad de XP — y en ambos casos la misión sigue abierta hasta que tomes la decisión correcta. Pierde los tres corazones y la semana se reinicia. Escalera: Junior → Líder de Delivery → Líder Senior → Leyenda de la IA.",
  in4:"Elige tu clase:",
  classes:{architect:["El Arquitecto","Ves sistemas. Los diagramas de Meridian te temen."],diplomat:["El Diplomático","Bilingüe, imperturbable. Los CFO firman cosas cerca de ti."],operator:["El Operador","Tú entregas. Los logs de producción susurran tu nombre."]},
  crTitle:"Crea tu héroe",lbName:"Nombre",lbOutfit:"Atuendo",lbShirt:"Camisa / saco",lbSkin:"Tono de piel",lbHairC:"Color de pelo",lbHairS:"Estilo de pelo",begin:"Fichar",
  outfits:[["casual","Casual"],["formal","Formal 👔"]],styles:[["cap","Corto"],["long","Largo"],["curly","Rizado"],["buzz","Rapado"],["spiky","Puntas"],["pony","Coleta"],["afro","Afro"],["mohawk","Cresta"],["braids","Trenzas"],["flat","Corte plano"],["buns","Chonguitos"],["edgar","Edgar"],["fade","Degradado"],["mullet","Mullet"],["broccoli","Brócoli"],["bald","Sin pelo"]],
  worldTag:"Meridian HQ · busca los ❗",
  hintSwipe:"Toca cualquier parte de la pantalla y arrastra para caminar · suelta para detenerte · ⚙️ para cambiar controles.",
  hintJoy:"Joystick o flechas para moverte · acércate a un compañero con ❗ y habla · ⚙️ para cambiar controles.",
  hintPad:"Cruceta o flechas para moverte · acércate a un compañero con ❗ y habla · ⚙️ para cambiar controles.",
  setTitle:"Ajustes",lbCtl:"Controles de movimiento",swipeB:"👆 Deslizar",joyB:"🕹️ Joystick",padB:"✛ Cruceta",lbLang:"Idioma",lbAdm:"Modo admin — toca casillas para remodelar la oficina",admOff:"Apagado",admOn:"🛠️ Activo",openLab:"📝 Laboratorio de textos",closeSet:"Listo",
  brushes:["Piso","Pared","Escritorio","Planta","Tapete","Puerta","Mesa","Refri","Estufa","Persona"],
  nmTitle:"Nuevo personaje",nmLb:"Ponles nombre — algunos nombres traen magia",nmOk:"✨ Crear",nmCancel:"Cancelar",
  npcMade:n=>n+" se mudó al barrio.",npcGone:"Se mudó a otra parte.",npcFull:"El barrio está lleno (máx. 12 amigos).",
  nmEditTitle:"Editar personaje",nmSave:"💾 Guardar",nmLook:"🎲 Otro look",nmOut:"📦 Mudanza",npcSaved:"Actualizado.",npcLook:"¡Look nuevo!",npcLease:"Tienen contrato — los vecinos originales se quedan.",
  chill:["Buen día para estar parado justo aquí.","No estorbo. SOY el camino.","El tranvía llegó tarde una vez. Una.",
   "Dicen que el perro de la oficina lleva mejor agenda que yo.","Aquí, vibrando. Es todo un oficio si lo haces bien.",
   "Las jacarandas solo florecen así cuando la semana va bien."],
  obraUp:"🏗️ ¡Avance! La obra de enfrente va tomando forma.",
  pigeon:["Curucucú.","La paloma juzga tu técnica para cruzar.","Estaba aquí antes que la ciudad. Seguirá después."],
  loro:["¡Ándale, jefe!","Lorenzo supervisa. Lorenzo aprueba.","¡Qué bonito trabajo!"],
  gato:["Mrrrp. El gato callejero lo permite.","Una oreja se mueve. Has sido reconocido.","La cuadrilla le da sobras de tamal. Él manda en esta obra."],
  mariposa:["Se posa en una flor, solo para ti.","Alas como papel picado.","Da una vuelta lenta alrededor de tu cabeza. Bendecido."],
  colibri:["Se queda flotando a un brazo de ti, inspeccionándote. Apruebas.","Un helicopterito esmeralda con opiniones.","Doña Rosa dice que la visita de un colibrí anuncia buenas noticias."],
  tlTitle:"Laboratorio de textos",tlHint:"Edita nombres, títulos de misiones y frases de choque (JSON). Aplica al idioma actual.",tlApply:"Guardar",tlClose:"Cerrar",tlOk:"Textos actualizados.",tlErr:"Ese JSON no se pudo leer — no cambió nada.",
  levels:["Junior","Líder de Delivery","Líder Senior","LEYENDA DE LA IA"],
  quest:"Misión",followup:" · seguimiento",codexLb:"📜 Códice",
  okH:"⚔️ MISIÓN CUMPLIDA",midH:"🟡 ENTREGADO CON INCIDENTES",badH:"💔 RESBALÓN — tu reputación sufre",
  lvlUp:"⬆ SUBISTE DE NIVEL — ahora eres ",
  nextBack:"Volver a la oficina",nextEnd:"Reclama tu título",nextDoom:"Enfrenta las consecuencias",
  talkPre:"💬 ",
  tut1:"Este eres tú. Muévete con el joystick o las flechas.",tut2:"Escritorios, plantas y paredes solo bloquean — los compañeros con ❗ tienen misiones. Acércate y habla.",
  admToast:"Admin activado. Elige un pincel y toca casillas. Un gran poder conlleva la capacidad de encerrarte a ti mismo.",
  undoLb:"Deshacer",undoToast:"Edición deshecha.",undoEmpty:"Nada que deshacer.",
  tlFindPh:"Buscar texto…",tlNoHit:"Sin coincidencias.",
  dog:["¡Guau!","Frederick aprueba.","Frederick te pastorea de vuelta al trabajo."],
  treatLb:"🦴 Premio a Frederick",fredHeart:"Frederick: ❤",
  petCat:"🐾 Acariciar a Canela",petPig:"🐾 Saludar a Paloma",petLoro:"🦜 Saludar a Lorenzo",petGato:"🐾 Acariciar al gato callejero",petFly:"🦋 Observar la mariposa",petColi:"🌺 Observar al colibrí",
  fredUnlock:"Frederick ya confía en ti… y tiene papeleo. 🐾 Misión secreta desbloqueada — dale otro premio para abrirla.",
  carePackToast:"📦 Nuevo en ⚙️ → Exportar: el kit de cuidados de Frederick — su ficha + recordatorios, listos para tu propia mascota.",
  fredDoneToast:"🎀 Mod desbloqueado: el pañuelo rojo de Frederick.",
  locs:{hq:"Meridian HQ",f2:"Piso 2 · Expansión",st:"Calle Meridian",lc:"La Cocina",lo:"La Obra · Estudio",ex:"Calle Dos · Cuadra de expansión",me:"El Mercado Robles",pk:"El Parque 🌈"},
  chat:{beto:["El jueves colamos la losa de El Mercado. Don Güero manda saludos.","Dos semanas más y esta cuadra tiene abarrotes, primo."],
        kike:["Muros derechos, prompts derechos — la misma disciplina.","La IA hizo el despiece de materiales. Revisé cada línea. Ya somos amigos."],
        mari:["Desde la grúa se ve el plan completo de Güero.","La IA ordena los izajes — peso, viento, orden. Suavecito todo el día."],
        chava:["Chile. Todo es chile. Es el botón más rápido, güey.","Doña Chelo dice que rompí los números. Yo digo que los números me rompieron a mí.","Frijol se lleva los recortes. Frijol no ha trabajado ni un día."]},
  arrive:{hq:"Meridian HQ.",f2:"Piso 2 — espacio de expansión. Tranquilo por aquí… por ahora.",st:"Nivel de calle. Cuidado con el cruce.",lc:"La Cocina — huele a consomé y a oportunidad.",lo:"El estudio de La Obra — tú ayudaste a construirlo. Cada dibujo de aquí se vuelve un edificio.",ex:"Calle Dos — el pueblo crece al este. El Mercado va subiendo.",me:"El Mercado Robles — cilantro, cumbia en el radio y un negocio con opiniones.",pk:"El Parque — pasto, río y puente arcoíris. Aquí no hay reloj."},
  trolley:{title:"🚋 Tranvía del Barrio",note:"La línea MQT — cada distrito, un solo viaje. ¿A dónde vamos?",here:"estás aquí",soon:"Barrio Norte — próximamente",close:"Quedarme aquí"},
  cat:["Mrrp.","Canela parpadea despacio. Estás aceptado.","La inspectora de salubridad no sabe de Canela. Que siga así."],
  endGo:"▶ Lunes — Semana Dos",
  weekTwoToast:"Lunes, 8am. Doña Chelo abre la reja del lote suroeste. Tres vidas, semana nueva.",
  mepi1:"Sábado, hora de cerrar. Doña Chelo cuenta la caja dos veces, como lo ha hecho por treinta años, y esta vez el número coincide con lo que la pantalla dijo toda la semana. “No me construiste un robot,” dice. “Me construiste un martes en el que puedo confiar.” Frijol duerme sobre la báscula. Corren los créditos.",
  mepi2:"Sábado, hora de cerrar. Algo pegó, algo Nando volvió a hacer a mano sin decir nada. Doña Chelo se encoge de hombros. “La mitad sirve. Es más que el anterior.” Escribe tu nombre en la pared junto a la caja, al lado del permiso. Corren los créditos.",
  mepi3:"Sábado, hora de cerrar. El mercado te sobrevivió. Chava sigue cobrando todo como chile y el piloto es una carpeta que nadie abre — pero Doña Chelo igual te da una bolsa de pan dulce. “Vuelve cuando lo hayas pensado.” Corren los créditos.",
  expBtn:"📤 Exportar (beta)",expTitle:"Exportar (beta)",
  expHint:"Esqueleto v1 — tus datos de juego como JSON, listos para copiar. Futuro: documentos tipados desde trabajo real (reporte de decisiones), envío por correo, exportar conversaciones.",
  expCopy:"Copiar",expCopied:"Copiado al portapapeles.",
  exTabJson:"Datos de juego",exTabCare:"🐾 Kit de cuidados",exIcs:"📅 Recordatorios (.ics)",
  exTabRep:"📄 Reporte de decisiones",exDl:"⬇️ Descargar (.md)",
  repHint:"Cada decisión que tomaste, redactada como pieza de portafolio — la pregunta, tu respuesta, el concepto que puso a prueba y por qué funcionó. Cópialo, o descarga el Markdown y entrégalo en una entrevista.",
  repHead:(n,lv,x,mx,he,dt)=>`# Reporte de Decisiones — ${n}

*Meridian Quest · criterio bajo presión · ${dt}*

**Nivel:** ${lv}  ·  **XP:** ${x}/${mx}  ·  **Calificación:** ${he}`,
  repSum:(d,q,pct)=>`**${d} decisiones en ${q} misiones — ${pct}% resueltas al primer intento.**`,
  repEmpty:"Aún no hay decisiones registradas. Responde una misión y este reporte se escribe solo.",
  repRole:(c,q,pct)=>`${c} ${c===1?"decisión":"decisiones"} en ${q} ${q===1?"misión":"misiones"} · ${pct}% al primer intento`,
  repL:{roles:"Roles practicados",side:"Misión personal",
    question:"Pregunta",call:"Tu decisión",verdict:"Veredicto",why:"Por qué",
    ok:"✅ Buena decisión",mid:"◐ Crédito parcial",bad:"✕ Fallo",
    advanced:"Correcto — avanzaste al seguimiento.",
    concepts:"Conceptos practicados",attempts:"intentos",attempt:"intento",
    foot:"Generado por Meridian Quest — un gimnasio de práctica, no un certificado."},
  careHint:"El sistema de operaciones de Frederick como entregable real — copia la ficha, descarga los recordatorios recurrentes y pon los datos de tu propia mascota.",
  carePack:(n,tr,p)=>`# 🐾 KIT DE CUIDADOS DE ${p.n.toUpperCase()}
A cargo de ${n} · Meridian Labs
Una sola fuente de verdad para una gran mascota.

## Diario
- ${p.am}  Desayuno
- Paseo matutino — 20 min
- ${p.pm}  Cena
- Paseo vespertino — 20 min
- Premios: máx. 3 al día (premios dados a Frederick en el juego: ${tr})

## Recurrente — si se repite, lleva recordatorio
- Pulgas/garrapatas + desparasitante ... mensual, el día 1
- Peluquería ........................... cada 8 semanas
- Pesaje ............................... cada 3 meses
- Chequeo veterinario + vacunas ........ anual (agenda con 2 semanas de anticipación)
- Día de lote de contenido ............. mensual: la IA redacta, un humano aprueba

## Reglas de la casa (según lo decidido en la misión)
1. Esta ficha es la única fuente de verdad — no el refri, no la cabeza de tres personas.
2. La memoria no es un sistema — cada ciclo de arriba vive en un calendario compartido (ve el .ics).
3. Una lista compartida; quien dé de comer, la marca.
4. Nada se publica como ${p.n} sin aprobación humana. ${p.n} no puede aprobar. ${p.n} es una gran mascota.`,
  careEvents:pn=>["🐾 Pulgas/garrapatas + desparasitante — "+pn,"🐾 Peluquería — "+pn,"🐾 Pesaje — "+pn,"🐾 Chequeo veterinario + vacunas — "+pn,"📸 Día de contenido de "+pn],
  petPh:"Nombre de la mascota",
  wdTitle:"🧵 El Drop de Xochi",wdNote:"Recién salido del tech pack — viste al barrio. Frederick ronda el HQ; Canela reina en La Cocina. Los cambios se guardan al instante.",
  wdBandana:"Bandana",wdCollar:"Collar",wdCape:"Capa",
  wdUnlockToast:"🧵 Vestidor desbloqueado — en ⚙️ Ajustes, o con Xochi cuando venzas su misión.",
  wdBtn:"🧵 Vestidor",
  tpBtn:"🎫 Pase del Tranvía",tpTitle:"🎫 Pase del Tranvía",
  tpNote:"Tu partida, sellada como pase de tranvía. Escanea el código con la cámara de tu otro dispositivo, o comparte el pase — al abordar allá siempre se pregunta primero.",
  tpShare:"📤 Compartir pase",tpCopy:"🔗 Copiar enlace",tpCopied:"Enlace del pase copiado.",
  tpFoundLb:"🎫 Pase del Tranvía encontrado",
  tpFoundTx:(n,x,d,q)=>`${n} llegó en el tranvía — ${x} XP, ${d}/${q} misiones.`,
  tpReplace:n=>`Abordar reemplaza la partida de este dispositivo (${n}).`,
  tpBoard:"🎫 Abordar con esta partida",tpSkip:"Conservar la partida de este dispositivo",
  mpBtn:"🌐 Multijugador 🚧",mpTitle:"🌐 Multijugador",
  mpNote:"🚧 En construcción. La cuadrilla del MQT está tendiendo vías hacia Barrio Norte — un día otros consultores rondarán estas calles contigo. Por ahora, la oficina es toda tuya. (El casco no se quita hasta que abra la línea.)",
  lbTheme:"Tema de color",
  updToast:"¡actualizado! Hay cosas nuevas.",lbCam:"Cámara",camTop:"🗺️ Cenital",camFront:"🏘 Frontal 2.5D",camIso:"◆ Isométrica",cam3d:"⛰ 3D",
  ballLb:"🎾 Lanza la pelota",ballNoRoom:"No hay espacio para lanzar aquí.",
  fetchYes:["¡Entregada! Un poco babeada, totalmente perfecta.","La trae como si fuera toda su carrera.","Recuperada. La cola dice que otra vez."],
  fetchNo:["Mira la pelota. Te mira a ti. Se sienta.","La pelota rueda. Él decidió que es problema de la pelota.","Hoy no. Es un perro de principios."],
  howl:"AUUUUUU…",
  beagleTreat:["¡Un premio! La cola despega.","Lo acepta con cuidado, como un caballero.","Crunch. Eres su persona favorita por una hora.","Recargado — ahorita te trae lo que sea."],
  loveLb:"💗 Te quiero",
  loveLines:["Todo el cuerpo se le mueve. Lo sabe. Siempre lo ha sabido.","Recarga la cabeza en tu mano. Mensaje recibido.","Golpecito de cola. Parpadeo lento. Yo también te quiero, dice el perro."],
  leashLb:"🦮 ¡Al parque!",leashToast:n=>`${n} toma la correa con el hocico. Él conoce el camino — por el puente arcoíris.`,
  parkArrive:"🌈 ¡El Parque! Lanza la pelota, comparte un premio, escucha los aullidos — aquí no hay reloj.",
  bandLb:"🎀 Bandana",bandToast:"🎀 ¡Nuevo look!",bandOff:"🎀 Al natural.",
  adoptLb:"🏠 Adopta un perro",adoptAsk:"Nombra a tu nuevo mejor amigo:",adoptGo:"🐶 Bienvenido a casa",adoptX:"Todavía no",
  adoptDone:n=>`🐶 ${n} ya está en casa. El parque acaba de mejorar.`,
  parkFull:"El parque está lleno — cuatro perros ya son muchos perros.",
  parkTitle:"🌈 Un día en El Parque",
  parkSum:(f,t,h,d)=>`🎾 ${f} ${f===1?"entrega":"entregas"} · 🦴 ${t} ${t===1?"premio":"premios"} · 🐶 ${h} ${h===1?"aullido":"aullidos"} · 🕳 ${d} ${d===1?"hoyo":"hoyos"}`,
  parkLove:"Te quiere. Ese era todo el juego.",
  parkTeaser:"Un día Sonny tendrá su propio juego completo. Este parque es el adelanto.",
  parkClose:"↩ De vuelta a la ciudad",isoEdit:"Cambia la cámara a Cenital para editar casillas.",lbMusic:"Música",musOn:"🔊 Activa",musOff:"🔇 Silenciada",tunes:["🎼 Auto","Lo-fi","Campanas","Marimba","Atardecer"],
  themes:{meridian:"🏢 Meridian",forest:"🌿 Bosque",fairy:"🧚 Hada",sunset:"🌇 Atardecer",custom:"✨ Personalizado"},
  teOpen:"🎨 Editor de temas",teTitle:"🎨 Editor de temas",
  teFrom:"Parte de un preset (se clona en ✨ Personalizado)",teModeLb:"Variante en edición",
  teFix:"🪄 Auto-ajustar contraste",
  teSaved:"✨ Paleta guardada — elígela cuando quieras en Tema de color.",tePalsLb:"Paletas guardadas",teNamePh:"Nombre de la paleta",palFull:"El ropero está lleno (8 paletas) — saca una primero.",palNames:{meridian:"Meridian",forest:"Bosque",fairy:"Hada",sunset:"Atardecer"},teFixed:"🪄 Colores de texto ajustados hasta que cada par pasa la auditoría de contraste.",
  retryNote:"❗ Esta sigue abierta — vuelve y toma la mejor decisión.",
  retryNoteFred:"🦴 Frederick reabrirá la carpeta por otro premio.",
  mapTitle:"Mapa del pueblo",vmF2:"Piso 2",vmHQ:"Meridian HQ",vmSt:"Calle Meridian",vmLc:"La Cocina 🌶️",
  vmSite0:"🚧 Obra en construcción",vmSite2:"La Obra · Estudio 📐",vmPlots:"Lotes reservados — El Mercado y más",vmHere:"◉ estás aquí",
  goTitle:"🕯️ La semana se te fue",
  goEpi:"Priya te encuentra en el estacionamiento. «Tres malas decisiones y el piso dejó de confiar en ti. Eso es la semana — no es el trabajo.» El capítulo cierra donde quedó: lo que dejaste sin contestar se queda sin contestar, y queda en el expediente. «Mismo escritorio el lunes. Esta vez ya leíste el Códice.»",
  mgoEpi:"Sábado. Doña Chelo recibe las llaves de vuelta sin rencores y con una bolsa de pan dulce. «Aprendiste en mi piso. Para eso está el piso.» El mercado se queda con lo que terminaste y olvida lo demás. Corren los créditos.",
  endStay:"↩ De vuelta a la ciudad",
  endStayToast:"La ciudad es tuya para caminarla. Nada pendiente por contestar — por ahora.",
  replayArm:"⚠️ Toca otra vez para borrar todo",
  endScore:(x,m,h)=>`${x}/${m} XP · ${h}/3 corazones intactos`,
  endGrade:(x,m,g)=>`${x}/${m} XP · ${g}`,
  grades:["la libraste","buen trabajo","impecable — al primer intento, casi siempre"],
  lbStakes:"Riesgo (admin)",stkNone:"Ninguno",stkHearts:"❤ Corazones",
  stkToast:m=>m==="hearts"?"Corazones encendidos. Una mala decisión cuesta uno — nada más.":"Corazones apagados. No hay nada que perder salvo la calificación.",goScore:(x,d,n)=>`${x} XP · ${d}/${n} misiones completadas`,
  epi1:"Viernes, 6pm. La VP se pone de pie cuando entras. «Semana impecable — y caminaste tu propio camino. El programa de agentes es tuyo.» Créditos finales — hasta la Semana Dos.",
  epi2:"Viernes, 6pm. «Buena semana», dice la VP. «Se entregaron algunos incidentes, pero el piso fue tuyo.» Priya asiente cuando sales. La Semana Dos se acerca.",
  epi3:"Viernes, 6pm. Sobreviviste — apenas. La VP desliza el Códice de vuelta por la mesa: «Estudia. Corre la semana otra vez. Meridian cree en las segundas partidas.»",
  replay:"Nueva partida +",replayToast:n=>`De vuelta, ${n}. Misma oficina, héroe con más calle.`,
  contBtn:(n,x,d)=>`▶ Continuar como ${n} — ${x} XP, ${d}/${QES.length} misiones`,
  langQuick:"🌐 English",
  flavor:{D:["Solo un escritorio. El monitor te juzga igual.","El escritorio de un colega. Su kombucha, sus reglas."],K:["La barra de café. Tierra sagrada.","La cafetera. Ha visto cosas."],P:["Una planta en maceta. Hace lo que puede.","El ficus de la oficina. Moral estructural."],"#":["Una pared. Argumento sólido.","Eso es una pared. Hasta las leyendas respetan las paredes."],"+":["Una puerta. Se abre caminando a través de ella. Tecnología.","Puerta detectada. Puedes pasar."],B:["La fachada del edificio. Sólida. Corporativa.","Ladrillo. Estaba aquí antes que tú y seguirá después."],F:["Cerca de obra. Casco obligatorio más allá."],G:["Vigas de acero. El futuro tiene andamios."],C:["Un cono de tráfico. Respétalo."],X:["🚧 En construcción — La Cocina (restaurante), El Mercado (abarrotes) y La Obra (oficina de construcción) abren aquí pronto."],T:["Una mesa del comedor. El mantel no es negociable.","Reservada. Probablemente para Canela."],W:["El cuarto frío. El pronóstico de Chuy está pegado ahí. Es ley.","Almacén frío. Donde los márgenes viven o mueren."],V:["La estufa. Seis quemadores de diplomacia de consomé.","Caliente. Dominio de Chuy. Pregunta antes de tocar."],A:["Una mesa de dibujo. Primero el boceto a mano, luego el render con IA — el criterio sigue siendo humano.","Trabajo en curso. Mide dos veces, promptea una."],U:["El muro de planos. Los planos: la salida estructurada original.","Cada edificio de esta calle fue primero un dibujo aquí."],Q:["La fachada de La Cocina. El toldo solito sube la plusvalía de la cuadra.","¿Hueles eso? Es el consomé de Rosa llamándote."],J:["Una jacaranda. La ciudad las planta; la ciudad discute por los pétalos.","Sombra de jacaranda. Gratis, y mejor que cualquier sala de juntas."]}
 }
};
